# Generated by Django 4.2.25 on 2026-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('important', 'Important'), ('ideas', 'Ideas'), ('meeting', 'Meeting')], default='work', max_length=20),
        ),
    ]
