# Generated by Django 4.2.25 on 2026-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_category_alter_note_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='snippet',
            field=models.CharField(blank=True, help_text='Text-only preview of content', max_length=500, null=True),
        ),
    ]
