# Generated by Django 4.2.4 on 2023-09-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_company_task_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
    ]
