# Generated by Django 4.2.4 on 2025-09-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('todo', '0002_rename_task_name_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.member'),
        ),
    ]
