# Generated by Django 5.2.7 on 2025-11-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
        ('todo', '0003_task_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed', 'due_date'], name='todo_task_complet_bf5d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'completed'], name='todo_task_due_dat_1648b1_idx'),
        ),
    ]
