# Generated by Django 4.2.25 on 2025-11-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_cartitem'),
        ('todo', '0004_alter_task_completed_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='authentication.member'),
        ),
    ]
