# Generated by Django 4.2.25 on 2025-11-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_taskcomment_alter_task_options_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
