# Generated by Django 4.2.4 on 2023-09-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_contact_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contact_company_id',
        ),
    ]
