# Generated by Django 5.2.7 on 2025-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_cartitem'),
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
        ('todo', '0007_alter_task_completed_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['member', 'completed', 'priority', 'due_date'], name='todo_task_member__af86db_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'completed', 'member'], name='todo_task_created_bec7de_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name'], name='todo_task_name_88a8ae_idx'),
        ),
    ]
