# Generated by Django 4.2.4 on 2023-09-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_task_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
    ]
