# Generated by Django 4.2.25 on 2025-12-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_exchangerate'),
        ('todo', '0008_task_todo_task_member__af86db_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Task Created'), ('completed', 'Task Completed'), ('reopened', 'Task Reopened'), ('priority_changed', 'Priority Changed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned To'), ('due_date_changed', 'Due Date Changed'), ('description_updated', 'Description Updated'), ('name_updated', 'Name Updated')], max_length=30)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='todo.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to='authentication.member')),
            ],
            options={
                'verbose_name_plural': 'Task Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='todo_taskac_task_id_89a83e_idx')],
            },
        ),
    ]
