# Generated by Django 4.2.25 on 2025-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_taskactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='on_hold',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
