# Generated by Django 4.2.4 on 2024-04-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='days_since_due',
        ),
    ]
