# Generated by Django 4.2.25 on 2026-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
        ('todo', '0012_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='authentication.member'),
        ),
    ]
