# Generated by Django 4.2.25 on 2026-02-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_task_id',
            field=models.CharField(blank=True, help_text='ID of the task in Google Tasks', max_length=255, null=True),
        ),
    ]
