# Generated by Django 5.2.7 on 2026-05-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_note_supplier_supplier_linked_company_and_more'),
        ('todo', '0014_task_google_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.supplier'),
        ),
    ]
