# Generated by Django 4.2.4 on 2025-10-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='delay_amount',
            field=models.IntegerField(default=3, help_text='Time to wait after previous email (ignored for Email 1, which sends immediately)'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='delay_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='days', help_text='Unit for delay time', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='days_after_previous',
            field=models.IntegerField(default=3, help_text='DEPRECATED: Use delay_amount and delay_unit instead'),
        ),
    ]
