# Generated by Django 5.2.7 on 2026-02-05 23:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
        ('email_automation', '0002_emailtemplate_delay_amount_emailtemplate_delay_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None)),
                ('cc_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('bcc_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.CharField(blank=True, max_length=300)),
                ('folder', models.CharField(choices=[('inbox', 'Gelen Kutusu'), ('sent', 'Gönderilen'), ('archive', 'Arşiv'), ('trash', 'Silinenler'), ('drafts', 'Taslaklar')], db_index=True, default='inbox', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='crm.contact')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_automation.emailaccount')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('gmail_attachment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_automation.email')),
            ],
            options={
                'verbose_name': 'Email Attachment',
                'verbose_name_plural': 'Email Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_account', 'folder'], name='email_autom_email_a_1df63a_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['company'], name='email_autom_company_747a61_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['contact'], name='email_autom_contact_53c9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['-sent_at'], name='email_autom_sent_at_724254_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['-received_at'], name='email_autom_receive_1c5b56_idx'),
        ),
    ]
