# Generated by Django 4.2.25 on 2026-02-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_automation', '0003_add_email_and_attachment_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-received_at', '-sent_at', '-created_at'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='gmail_attachment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
