# Generated by Django 5.2.7 on 2026-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
        ('email_automation', '0004_alter_email_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='user_emails_multi', to='crm.company'),
        ),
        migrations.AddField(
            model_name='email',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_emails_multi', to='crm.contact'),
        ),
    ]
