# Generated by Django 4.2.25 on 2026-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_automation', '0005_email_companies_email_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
