# Generated by Django 4.2.25 on 2026-09-05 23:34

from django.db import migrations


class Migration(migrations.Migration):
    """Release the mail models — state only.

    marketing/0080 renamed the physical tables and took ownership of them.
    These deletions must therefore touch state ONLY; letting them reach the
    database would drop the tables that migration just adopted, taking every
    email, attachment and campaign with them.

    The app itself stays installed as a migrations-only stub so the graph keeps
    resolving on databases that already applied 0001-0006.
    """

    dependencies = [
        ('email_automation', '0006_alter_email_is_read'),
        # marketing must adopt the tables before this releases the state,
        # otherwise a fresh build has nothing to rename.
        ('marketing', '0080_adopt_mail_models_from_email_automation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='emailaccount',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='emailattachment',
                    name='email',
                ),
                migrations.RemoveField(
                    model_name='emailcampaign',
                    name='company',
                ),
                migrations.RemoveField(
                    model_name='emailcampaign',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='emailtemplate',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='emailtemplate',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='receivedemail',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='sentemail',
                    name='campaign',
                ),
                migrations.RemoveField(
                    model_name='sentemail',
                    name='template',
                ),
                migrations.DeleteModel(
                    name='Email',
                ),
                migrations.DeleteModel(
                    name='EmailAccount',
                ),
                migrations.DeleteModel(
                    name='EmailAttachment',
                ),
                migrations.DeleteModel(
                    name='EmailCampaign',
                ),
                migrations.DeleteModel(
                    name='EmailTemplate',
                ),
                migrations.DeleteModel(
                    name='ReceivedEmail',
                ),
                migrations.DeleteModel(
                    name='SentEmail',
                ),
            ],
            database_operations=[],
        ),
    ]
