# Generated by Django 4.2.4 on 2025-02-14 15:21

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=True)),
                ('photo_files', models.FileField(blank=True, null=True, upload_to=marketing.models.product_directory_path)),
            ],
        ),
    ]
