# Generated by Django 4.2.4 on 2025-03-09 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='marketing.productcollection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_while_out_of_stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_weight',
            field=models.CharField(blank=True, choices=[('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g')], default=('lb', 'lb'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='crm.supplier'),
        ),
    ]
