# Generated by Django 4.2.4 on 2025-03-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_product_vendor_alter_product_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, null=True),
        ),
    ]
