# Generated by Django 4.2.4 on 2025-02-14 16:52

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_supplier_company_name_and_more'),
        ('marketing', '0004_collection_created_at_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=marketing.models.product_variants_default, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='crm.supplier'),
        ),
    ]
