# Generated by Django 4.2.4 on 2025-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_supplier_company_name_and_more'),
        ('marketing', '0005_alter_product_variants_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(blank=True, related_name='products', to='crm.supplier'),
        ),
    ]
