# Generated by Django 4.2.4 on 2025-02-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='supplier',
        ),
    ]
