# Generated by Django 4.2.4 on 2025-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_productvariantattributevalue_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=153153, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
