# Generated by Django 4.2.4 on 2025-03-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='product_variant',
        ),
    ]
