# Generated by Django 4.2.4 on 2025-03-26 17:51

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_remove_productfile_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to=marketing.models.product_file_directory_path, validators=[marketing.models.validate_file_size, marketing.models.validate_file_type]),
        ),
    ]
