# Generated by Django 4.2.4 on 2025-02-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_product_cost_productfile_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='sequence',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
