# Generated by Django 4.2.4 on 2025-02-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_remove_product_variants_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_weight',
            field=models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g')], default=('oz', 'oz')),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
