# Generated by Django 4.2.4 on 2025-02-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_product_unit_of_weight_productvariant_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_weight',
            field=models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g')], default=('lb', 'lb')),
        ),
    ]
