# Generated by Django 4.2.4 on 2025-05-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_remove_product_cost_productfile_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='sequence',
        ),
    ]
