# Generated by Django 4.2.4 on 2025-02-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_alter_product_unit_of_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Attribute Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Attribute Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.productvariantattribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='marketing.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
