# Generated by Django 4.2.4 on 2025-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_remove_productfile_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_inventory_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='datasheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_minimum_inventory_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
