# Generated by Django 4.2.4 on 2025-05-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_product_datasheet_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='datasheet_url',
            new_name='variant_datasheet_url',
        ),
    ]
