# Generated by Django 4.2.4 on 2025-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_rename_datasheet_url_productvariant_variant_datasheet_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_barcode',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_sku',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantattributevalue',
            name='value',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Attribute Value'),
        ),
    ]
