# Generated by Django 4.2.4 on 2025-02-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_productvariantattribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='product',
        ),
    ]
