# Generated by Django 4.2.4 on 2025-05-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_alter_product_barcode_alter_product_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantattributevalue',
            old_name='variant',
            new_name='product_variant',
        ),
        migrations.RenameField(
            model_name='productvariantattributevalue',
            old_name='attribute',
            new_name='product_variant_attribute',
        ),
        migrations.RenameField(
            model_name='productvariantattributevalue',
            old_name='value',
            new_name='product_variant_attribute_value',
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattributevalue',
            unique_together={('product_variant', 'product_variant_attribute')},
        ),
    ]
