# Generated by Django 4.2.4 on 2025-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0018_remove_productvariantattribute_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
