# Generated by Django 4.2.4 on 2025-06-01 08:54

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0018_rename_variant_productvariantattributevalue_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=marketing.models.product_category_directory_path, validators=[marketing.models.validate_file_size, marketing.models.validate_image_type]),
        ),
    ]
