# Generated by Django 4.2.4 on 2025-02-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_productvariant_cost_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cost',
        ),
    ]
