# Generated by Django 4.2.4 on 2025-06-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variants',
        ),
    ]
