# Generated by Django 4.2.4 on 2025-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_remove_product_cost_remove_productvariant_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
