# Generated by Django 4.2.4 on 2025-06-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_productfile_is_primary_productfile_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='is_primary',
        ),
    ]
