# Generated by Django 4.2.4 on 2025-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0098_remove_assetinventorygood_product'),
        ('marketing', '0022_productvariant_cost_productvariant_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
