# Generated by Django 4.2.4 on 2025-02-20 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_supplier_company_name_and_more'),
        ('marketing', '0023_remove_productfile_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=12, null=True)),
                ('barcode', models.CharField(blank=True, max_length=14, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('category', models.CharField(blank=True, default='uncategorized', null=True)),
                ('type', models.CharField(blank=True, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, choices=[('units', 'Unit'), ('mt', 'Meter'), ('kg', 'Kilogram')], default=('units', 'Unit'), null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('featured', models.BooleanField(default=True)),
                ('selling_while_out_of_stock', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_of_weight', models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g')], default=('lb', 'lb'))),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='marketing.collection')),
                ('vendor', models.ManyToManyField(blank=True, related_name='products', to='crm.supplier')),
            ],
        ),
    ]
