# Generated by Django 4.2.4 on 2025-06-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_remove_productfile_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattribute',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Attribute Name'),
        ),
    ]
