# Generated by Django 4.2.4 on 2025-06-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_alter_productvariantattribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattributevalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='marketing.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariantattributevalue',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='marketing.productvariant'),
            preserve_default=False,
        ),
    ]
