# Generated by Django 4.2.4 on 2025-02-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_productcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='ProductCollection',
        ),
    ]
