# Generated by Django 4.2.4 on 2025-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_sku',
            field=models.CharField(db_index=True, default=1, max_length=12),
            preserve_default=False,
        ),
    ]
