# Generated by Django 4.2.4 on 2025-02-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0027_rename_collection_productcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketing.productvariant'),
        ),
    ]
