# Generated by Django 4.2.4 on 2025-02-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_productfile_product_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantattributevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariantattributevalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='marketing.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattributevalue',
            unique_together={('product', 'variant', 'attribute')},
        ),
    ]
