# Generated by Django 4.2.4 on 2025-02-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0029_alter_productvariantattributevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='description',
        ),
    ]
