# Generated by Django 4.2.4 on 2025-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0029_remove_productfile_file_productfile_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
