# Generated by Django 4.2.4 on 2025-06-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_productfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
