# Generated by Django 4.2.4 on 2025-02-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_remove_productvariant_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name_plural': 'Product Variants'},
        ),
    ]
