# Generated by Django 4.2.4 on 2025-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0031_alter_productvariant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
    ]
