# Generated by Django 4.2.4 on 2025-08-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0032_alter_productcategory_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantattributevalue',
            unique_together={('product_variant_attribute', 'product_variant_attribute_value')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product_variant_attribute_values',
            field=models.ManyToManyField(related_name='variants', to='marketing.productvariantattributevalue'),
        ),
        migrations.AddField(
            model_name='productvariantattributevalue',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='productvariantattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantattributevalue',
            name='product_variant',
        ),
    ]
