# Generated by Django 4.2.4 on 2025-02-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0032_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='barcode',
            new_name='variant_barcode',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='cost',
            new_name='variant_cost',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='featured',
            new_name='variant_featured',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='variant_price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='quantity',
            new_name='variant_quantity',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='sku',
            new_name='variant_sku',
        ),
    ]
