# Generated by Django 4.2.4 on 2025-02-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0033_rename_barcode_productvariant_variant_barcode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantattributevalue',
            unique_together={('variant', 'attribute')},
        ),
        migrations.RemoveField(
            model_name='productvariantattributevalue',
            name='product',
        ),
    ]
