# Generated by Django 4.2.4 on 2025-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0033_alter_productvariantattributevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantattributevalue',
            name='code',
        ),
        migrations.AlterField(
            model_name='productvariantattributevalue',
            name='product_variant_attribute_value',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Attribute Value'),
        ),
    ]
