# Generated by Django 4.2.4 on 2025-02-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0034_alter_productvariantattributevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
