# Generated by Django 4.2.4 on 2025-08-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0034_remove_productvariantattributevalue_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='image',
            new_name='image_url',
        ),
    ]
