# Generated by Django 4.2.4 on 2025-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0036_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_sku',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
