# Generated by Django 5.2.7 on 2025-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0039_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantattributevalue',
            name='product_variant_attribute_value',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Attribute Value'),
        ),
    ]
