# Generated by Django 5.2.7 on 2025-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0040_alter_productvariantattributevalue_product_variant_attribute_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariantattributevalue',
            index=models.Index(fields=['product_variant_attribute'], name='marketing_p_product_5e14e4_idx'),
        ),
    ]
