# Generated by Django 5.2.7 on 2025-11-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0041_productvariantattributevalue_marketing_p_product_5e14e4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: En, Kumaş Türü, Kullanım Alanı', max_length=255, verbose_name='Özellik Adı')),
                ('value', models.CharField(help_text='Örn: 150cm, Tül, Gelinlik', max_length=500, verbose_name='Özellik Değeri')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='marketing.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='marketing.productvariant')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['sequence', 'name'],
                'indexes': [models.Index(fields=['product', 'name'], name='marketing_p_product_b0d44f_idx'), models.Index(fields=['product_variant', 'name'], name='marketing_p_product_0910eb_idx')],
            },
        ),
    ]
