# Generated by Django 5.2.7 on 2025-12-16 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_exchangerate'),
        ('marketing', '0042_productattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment text')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the review is approved and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketing.product')),
                ('web_client', models.ForeignKey(help_text='The user who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='authentication.webclient')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved'], name='marketing_p_product_696bb3_idx'), models.Index(fields=['web_client'], name='marketing_p_web_cli_3bba3f_idx')],
                'unique_together': {('web_client', 'product')},
            },
        ),
    ]
