# Generated by Django 4.2.25 on 2025-12-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0044_add_cost_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Fenomene verilecek benzersiz kod (örn: KARVEN10)', max_length=50, unique=True, verbose_name='İndirim Kodu')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Yüzde olarak indirim miktarı (örn: 10.00 için %10)', max_digits=5, verbose_name='İndirim Yüzdesi')),
                ('is_active', models.BooleanField(default=True, help_text='Kod aktif mi?', verbose_name='Aktif')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Bu kodla kaç başarılı sipariş oluşturuldu', verbose_name='Kullanım Sayısı')),
                ('influencer_name', models.CharField(blank=True, help_text='Bu kodu kullanacak fenomenin adı (opsiyonel)', max_length=100, verbose_name='Fenomen Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İndirim Kodu',
                'verbose_name_plural': 'İndirim Kodları',
                'ordering': ['-created_at'],
            },
        ),
    ]
