# Generated by Django 4.2.25 on 2026-01-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0045_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('title_tr', models.CharField(max_length=300, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Заголовок (RU)')),
                ('title_pl', models.CharField(blank=True, max_length=300, verbose_name='Tytuł (PL)')),
                ('excerpt_tr', models.TextField(verbose_name='Özet (TR)')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='Excerpt (EN)')),
                ('excerpt_ru', models.TextField(blank=True, verbose_name='Краткое описание (RU)')),
                ('excerpt_pl', models.TextField(blank=True, verbose_name='Streszczenie (PL)')),
                ('content_tr', models.TextField(verbose_name='İçerik (TR)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (EN)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Содержание (RU)')),
                ('content_pl', models.TextField(blank=True, verbose_name='Treść (PL)')),
                ('category_tr', models.CharField(max_length=100, verbose_name='Kategori (TR)')),
                ('category_en', models.CharField(blank=True, max_length=100, verbose_name='Category (EN)')),
                ('category_ru', models.CharField(blank=True, max_length=100, verbose_name='Категория (RU)')),
                ('category_pl', models.CharField(blank=True, max_length=100, verbose_name='Kategoria (PL)')),
                ('cover_image', models.URLField(blank=True, verbose_name='Kapak Resmi (Liste)')),
                ('hero_image', models.URLField(blank=True, verbose_name='Hero Resmi (Detay)')),
                ('author', models.CharField(default='Karven Home Collection', max_length=200)),
                ('published_at', models.DateField(verbose_name='Yayın Tarihi')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('cover', 'Kapak Resmi'), ('hero', 'Hero Resmi'), ('content', 'İçerik Resmi')], default='content', max_length=20)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketing.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Dosyası',
                'verbose_name_plural': 'Blog Dosyaları',
                'ordering': ['sequence', 'pk'],
            },
        ),
    ]
