# Generated by Django 4.2.25 on 2026-01-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0046_blogpost_blogfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
