# Generated by Django 4.2.25 on 2026-01-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0047_add_file_type_to_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='0 = sınırsız, 1 = tek kullanımlık', verbose_name='Maksimum Kullanım'),
        ),
        migrations.CreateModel(
            name='WebSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Abone e-posta adresi', max_length=254, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(help_text='Abone telefon numarası', max_length=20, unique=True, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='marketing.discountcode', verbose_name='İndirim Kodu')),
            ],
            options={
                'verbose_name': 'Bülten Aboneliği',
                'verbose_name_plural': 'Bülten Abonelikleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
