# Generated by Django 4.2.25 on 2026-01-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0050_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('units', 'Unit'), ('mt', 'Meter'), ('kg', 'Kilogram')], default='units', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_weight',
            field=models.CharField(blank=True, choices=[('lb', 'lb'), ('oz', 'oz'), ('kg', 'kg'), ('g', 'g')], default='lb', null=True),
        ),
    ]
