# Generated by Django 4.2.25 on 2026-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0051_alter_product_unit_of_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='video_thumb_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
