# Generated by Django 4.2.25 on 2026-02-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0052_add_video_thumb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='video_thumb_url',
        ),
    ]
