# Generated by Django 4.2.25 on 2026-02-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0053_remove_productfile_video_thumb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='footer_content',
            field=models.TextField(blank=True, help_text='e.g. &lt;script&gt;...&lt;/script&gt;', verbose_name='Extra Footer Content (JS)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='header_content',
            field=models.TextField(blank=True, help_text='e.g. &lt;style&gt;...&lt;/style&gt; or &lt;link&gt;', verbose_name='Extra Header Content (CSS/Meta)'),
        ),
    ]
