# Generated by Django 4.2.25 on 2026-02-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0063_assetcash_amount_assetcash_balance_base'),
        ('marketing', '0054_blogpost_footer_content_blogpost_header_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published_on_store',
            field=models.BooleanField(default=True, verbose_name='Mağazada Yayınla'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mağaza Adı')),
                ('domain', models.CharField(blank=True, help_text='Örn: magaza.com veya magaza.erp.com', max_length=255, null=True, unique=True, verbose_name='Alan Adı')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('favicon_url', models.URLField(blank=True, null=True, verbose_name='Favicon URL')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex kodu (örn: #FF5733)', max_length=50, verbose_name='Ana Renk')),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=50, verbose_name='İkincil Renk')),
                ('font_family', models.CharField(default='Inter', max_length=100, verbose_name='Yazı Tipi')),
                ('welcome_title', models.CharField(blank=True, max_length=255, verbose_name='Karşılama Başlığı')),
                ('welcome_text', models.TextField(blank=True, verbose_name='Karşılama Metni')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Başlığı')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Açıklaması')),
                ('active_theme', models.CharField(choices=[('classic', 'Klasik'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='modern', max_length=50, verbose_name='Aktif Tema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='accounting.book', verbose_name='İşletme')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sayfa Başlığı')),
                ('slug', models.SlugField(verbose_name='URL Yolu')),
                ('content', models.TextField(verbose_name='İçerik (HTML/JSON)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınla')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='marketing.store', verbose_name='Mağaza')),
            ],
            options={
                'verbose_name': 'Mağaza Sayfası',
                'verbose_name_plural': 'Mağaza Sayfaları',
                'ordering': ['sequence', 'title'],
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
