# Generated by Django 4.2.25 on 2026-02-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0055_product_is_published_on_store_store_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='book',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published_on_store',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
