# Generated by Django 4.2.25 on 2026-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0056_remove_store_book_and_more'),
    ]

    operations = [
        # Drop any pre-existing index from earlier migrations (0049) so that
        # AlterField's CREATE INDEX below doesn't collide on environments
        # where the index already exists.
        migrations.RunSQL(
            sql=(
                "DROP INDEX IF EXISTS marketing_product_title_a2adac67;"
                "DROP INDEX IF EXISTS marketing_product_title_a2adac67_like;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
