# Generated by Django 4.2.25 on 2026-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0058_restore_product_variant_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category_en',
            field=models.CharField(max_length=100, verbose_name='Category (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category_tr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategori (TR)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_tr',
            field=models.TextField(blank=True, verbose_name='İçerik (TR)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(verbose_name='Excerpt (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_tr',
            field=models.TextField(blank=True, verbose_name='Özet (TR)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=300, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Başlık (TR)'),
        ),
    ]
