# Generated by Django 5.2.7 on 2026-03-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0059_blogpost_english_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
