# Generated by Django 5.2.7 on 2026-03-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0060_add_variant_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_alt_text',
        ),
    ]
