# Generated by Django 5.2.7 on 2026-03-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0061_remove_variant_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='productfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
