# Generated by Django 5.2.7 on 2026-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0062_add_productfile_alt_text_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogfile',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
