# Generated by Django 4.2.25 on 2026-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0064_fix_unit_of_measurement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='video_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
