# Generated by Django 4.2.25 on 2026-04-17 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0064_fix_unit_of_measurement_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('hide_name', models.BooleanField(default=False, help_text='Show only initials')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Must be approved by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='The product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='guest_reviews', to='marketing.product')),
            ],
            options={
                'verbose_name': 'Guest Product Review',
                'verbose_name_plural': 'Guest Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketing.guestproductreview')),
            ],
        ),
    ]
