# Generated by Django 5.2.7 on 2026-04-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0065_add_video_thumbnail_to_productfile'),
        ('marketing', '0065_guestproductreview_guestreviewimage'),
    ]

    operations = [
    ]
