# Generated by Django 4.2.25 on 2026-04-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0066_merge_20260422_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantAttributeValueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='marketing.productvariantattributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value_images', to='marketing.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'attribute_value'], name='marketing_v_product_7ff7f4_idx')],
                'unique_together': {('product', 'attribute_value')},
            },
        ),
    ]
