# Generated by Django 4.2.25 on 2026-04-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0067_variantattributevalueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantattributevalueimage',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
