# Generated by Django 5.2.7 on 2026-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0068_variantattributevalueimage_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_packaged',
            field=models.BooleanField(default=False, help_text="Bu ürün paket halinde mi satılıyor? (12'li, 5'li vb.)"),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pakette kaç adet var? (is_packaged=True ise zorunlu)', null=True),
        ),
    ]
