# Generated by Django 4.2.25 on 2026-05-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0069_product_is_packaged_product_pack_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('volume', 'Volume / Quantity Tier')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Used only for percentage campaigns. Example: 15.00 = %15', max_digits=5, null=True)),
                ('end_date', models.DateField(blank=True, help_text='When the percentage discount expires (inclusive).', null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='marketing.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCampaignTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField()),
                ('max_qty', models.PositiveIntegerField(blank=True, help_text='Leave blank for an open-ended top tier (7500+).', null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='marketing.productcampaign')),
            ],
            options={
                'ordering': ['min_qty'],
            },
        ),
    ]
