# Generated by Django 5.2.7 on 2026-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0073_unique_variant_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='b2b_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_b2b_price',
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='Bakım talimatları — boş bırakılırsa ürün grubununki geçerli', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum sipariş miktarı — boş bırakılırsa ürün grubununki geçerli', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kar oranı % — boş bırakılırsa ürün grubununki geçerli', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='care_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Tahmini tedarik/teslim süresi (gün)', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu gruptaki ürünler için minimum sipariş miktarı (ürün bazında ezilebilir)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kar oranı % — maliyet üzerine eklenir (fiyat = maliyet × (1 + oran/100))', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='washing_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
