# Generated by Django 5.2.7 on 2026-07-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0074_remove_product_b2b_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care_instructions',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='care_instructions_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='washing_instructions_tr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
