# Generated by Django 5.2.7 on 2026-07-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0075_remove_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='washing_instructions',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='washing_instructions_tr',
        ),
    ]
