# Generated by Django 4.2.25 on 2026-08-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0078_mt_products_to_markiss_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_sku',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
