# Generated by Django 4.2.25 on 2026-09-05 23:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Adopt the mail models from the email_automation app.

    The tables already exist and hold live mail, so the CreateModel operations
    below are STATE ONLY — they tell Django these seven models (plus the two
    auto-created m2m tables) now belong to `marketing`. The database side just
    renames the physical tables, keeping every row in place.

    Two index details, both of which would otherwise desynchronise state from
    the database:

      * Postgres does not rename indexes when a table is renamed, and Django
        stores Meta index names in migration state. `email_autom_sent_at_...`
        is therefore renamed to the name this migration's state declares.

      * Email's other four Meta indexes are created here under their new
        names rather than renamed, which leaves the originals behind under
        their `email_autom_` spelling. 0082 drops those leftovers; doing it
        there rather than here means this migration stays exactly as it was
        applied, and the two paths — a database that ran this and a database
        built from scratch — converge on the same set of indexes.

    Auto-generated primary-key and foreign-key index names are left on their
    old spelling on purpose: Django finds those by introspecting columns, not
    by name, so renaming them buys nothing.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0019_company_created_by_contact_created_by'),
        ('marketing', '0079_alter_product_sku_alter_productvariant_variant_sku'),
        # The database_operations below RENAME the email_automation tables,
        # so those tables have to exist first. Without this the graph left
        # the two apps unordered, and a database built from scratch picked
        # this migration before email_automation had created anything:
        #
        #   ProgrammingError: relation "email_automation_emailaccount"
        #   does not exist
        #
        # which took out every local test run and any fresh deploy. The
        # reverse edge was already declared — email_automation.0007 waits
        # for this migration before releasing the models from its state —
        # so the full order is 0006 -> marketing.0080 -> 0007, no cycle.
        ('email_automation', '0006_alter_email_is_read'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Email',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                        ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                        ('from_email', models.EmailField(max_length=254)),
                        ('from_name', models.CharField(blank=True, max_length=200)),
                        ('to_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=list, size=None)),
                        ('cc_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                        ('bcc_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                        ('subject', models.CharField(max_length=500)),
                        ('body_text', models.TextField(blank=True)),
                        ('body_html', models.TextField(blank=True)),
                        ('snippet', models.CharField(blank=True, max_length=300)),
                        ('folder', models.CharField(choices=[('inbox', 'Gelen Kutusu'), ('sent', 'Gönderilen'), ('archive', 'Arşiv'), ('trash', 'Silinenler'), ('drafts', 'Taslaklar')], db_index=True, default='inbox', max_length=20)),
                        ('is_read', models.BooleanField(db_index=True, default=False)),
                        ('is_starred', models.BooleanField(default=False)),
                        ('is_important', models.BooleanField(default=False)),
                        ('sent_at', models.DateTimeField(blank=True, null=True)),
                        ('received_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('companies', models.ManyToManyField(blank=True, related_name='user_emails_multi', to='crm.company')),
                        ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='crm.company')),
                        ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emails', to='crm.contact')),
                        ('contacts', models.ManyToManyField(blank=True, related_name='user_emails_multi', to='crm.contact')),
                    ],
                    options={
                        'verbose_name': 'Email',
                        'verbose_name_plural': 'Emails',
                        'ordering': ['-received_at', '-sent_at', '-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='EmailCampaign',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('stopped', 'Stopped - Reply Received')], default='active', max_length=20)),
                        ('emails_sent', models.IntegerField(default=0)),
                        ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                        ('next_email_scheduled_at', models.DateTimeField(blank=True, null=True)),
                        ('reply_received', models.BooleanField(default=False)),
                        ('reply_received_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign', to='crm.company')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Email Campaign',
                        'verbose_name_plural': 'Email Campaigns',
                    },
                ),
                migrations.CreateModel(
                    name='EmailTemplate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('sequence_number', models.IntegerField(choices=[(1, 'Email 1 - Introduction'), (2, 'Email 2 - Follow-up'), (3, 'Email 3 - Value Proposition'), (4, 'Email 4 - Case Study'), (5, 'Email 5 - Last Chance'), (6, 'Email 6 - Final Follow-up')])),
                        ('subject', models.CharField(max_length=200)),
                        ('body', models.TextField(help_text='Use {{company_name}}, {{contact_name}} as placeholders')),
                        ('delay_amount', models.IntegerField(default=3, help_text='Time to wait after previous email (ignored for Email 1, which sends immediately)')),
                        ('delay_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='days', help_text='Unit for delay time', max_length=10)),
                        ('days_after_previous', models.IntegerField(default=3, help_text='DEPRECATED: Use delay_amount and delay_unit instead')),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['sequence_number'],
                        'unique_together': {('user', 'sequence_number')},
                    },
                ),
                migrations.CreateModel(
                    name='SentEmail',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('recipient_email', models.EmailField(max_length=254)),
                        ('recipient_name', models.CharField(blank=True, max_length=200)),
                        ('subject', models.CharField(max_length=200)),
                        ('body', models.TextField()),
                        ('gmail_message_id', models.CharField(blank=True, max_length=200)),
                        ('gmail_thread_id', models.CharField(blank=True, max_length=200)),
                        ('sent_at', models.DateTimeField(auto_now_add=True)),
                        ('opened', models.BooleanField(default=False)),
                        ('replied', models.BooleanField(default=False)),
                        ('replied_at', models.DateTimeField(blank=True, null=True)),
                        ('error_message', models.TextField(blank=True)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='marketing.emailcampaign')),
                        ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailtemplate')),
                    ],
                    options={
                        'verbose_name': 'Sent Email',
                        'verbose_name_plural': 'Sent Emails',
                        'ordering': ['-sent_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ReceivedEmail',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('sender_email', models.EmailField(max_length=254)),
                        ('sender_name', models.CharField(blank=True, max_length=200)),
                        ('subject', models.CharField(max_length=500)),
                        ('body', models.TextField()),
                        ('gmail_message_id', models.CharField(max_length=200, unique=True)),
                        ('gmail_thread_id', models.CharField(blank=True, max_length=200)),
                        ('received_at', models.DateTimeField()),
                        ('processed', models.BooleanField(default=False)),
                        ('is_reply', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to='marketing.emailcampaign')),
                    ],
                    options={
                        'verbose_name': 'Received Email',
                        'verbose_name_plural': 'Received Emails',
                        'ordering': ['-received_at'],
                    },
                ),
                migrations.CreateModel(
                    name='EmailAttachment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('filename', models.CharField(max_length=255)),
                        ('file_url', models.URLField(max_length=500)),
                        ('file_size', models.PositiveIntegerField(default=0)),
                        ('content_type', models.CharField(blank=True, max_length=100)),
                        ('gmail_attachment_id', models.TextField(blank=True, null=True)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketing.email')),
                    ],
                    options={
                        'verbose_name': 'Email Attachment',
                        'verbose_name_plural': 'Email Attachments',
                        'ordering': ['uploaded_at'],
                    },
                ),
                migrations.CreateModel(
                    name='EmailAccount',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('email_address', models.EmailField(max_length=254)),
                        ('access_token', models.TextField(blank=True)),
                        ('refresh_token', models.TextField(blank=True)),
                        ('token_expiry', models.DateTimeField(blank=True, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Email Account',
                        'verbose_name_plural': 'Email Accounts',
                    },
                ),
                migrations.AddField(
                    model_name='email',
                    name='email_account',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.emailaccount'),
                ),
                migrations.AddIndex(
                    model_name='email',
                    index=models.Index(fields=['email_account', 'folder'], name='marketing_e_email_a_16ccdc_idx'),
                ),
                migrations.AddIndex(
                    model_name='email',
                    index=models.Index(fields=['company'], name='marketing_e_company_02534c_idx'),
                ),
                migrations.AddIndex(
                    model_name='email',
                    index=models.Index(fields=['contact'], name='marketing_e_contact_cfcec0_idx'),
                ),
                migrations.AddIndex(
                    model_name='email',
                    index=models.Index(fields=['-sent_at'], name='marketing_e_sent_at_4f4526_idx'),
                ),
                migrations.AddIndex(
                    model_name='email',
                    index=models.Index(fields=['-received_at'], name='marketing_e_receive_e17293_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "email_automation_emailaccount" RENAME TO "marketing_emailaccount";',
                        'ALTER TABLE "email_automation_emailtemplate" RENAME TO "marketing_emailtemplate";',
                        'ALTER TABLE "email_automation_emailcampaign" RENAME TO "marketing_emailcampaign";',
                        'ALTER TABLE "email_automation_sentemail" RENAME TO "marketing_sentemail";',
                        'ALTER TABLE "email_automation_receivedemail" RENAME TO "marketing_receivedemail";',
                        'ALTER TABLE "email_automation_email" RENAME TO "marketing_email";',
                        'ALTER TABLE "email_automation_emailattachment" RENAME TO "marketing_emailattachment";',
                        'ALTER TABLE "email_automation_email_companies" RENAME TO "marketing_email_companies";',
                        'ALTER TABLE "email_automation_email_contacts" RENAME TO "marketing_email_contacts";',
                        'ALTER INDEX "email_autom_sent_at_724254_idx" RENAME TO "marketing_e_sent_at_4f4526_idx";',
                        'CREATE INDEX IF NOT EXISTS "marketing_e_email_a_16ccdc_idx" ON "marketing_email" ("email_account_id", "folder");',
                        'CREATE INDEX IF NOT EXISTS "marketing_e_company_02534c_idx" ON "marketing_email" ("company_id");',
                        'CREATE INDEX IF NOT EXISTS "marketing_e_contact_cfcec0_idx" ON "marketing_email" ("contact_id");',
                        'CREATE INDEX IF NOT EXISTS "marketing_e_receive_e17293_idx" ON "marketing_email" ("received_at" DESC);',
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "marketing_e_receive_e17293_idx";',
                        'DROP INDEX IF EXISTS "marketing_e_contact_cfcec0_idx";',
                        'DROP INDEX IF EXISTS "marketing_e_company_02534c_idx";',
                        'DROP INDEX IF EXISTS "marketing_e_email_a_16ccdc_idx";',
                        'ALTER INDEX "marketing_e_sent_at_4f4526_idx" RENAME TO "email_autom_sent_at_724254_idx";',
                        'ALTER TABLE "marketing_emailaccount" RENAME TO "email_automation_emailaccount";',
                        'ALTER TABLE "marketing_emailtemplate" RENAME TO "email_automation_emailtemplate";',
                        'ALTER TABLE "marketing_emailcampaign" RENAME TO "email_automation_emailcampaign";',
                        'ALTER TABLE "marketing_sentemail" RENAME TO "email_automation_sentemail";',
                        'ALTER TABLE "marketing_receivedemail" RENAME TO "email_automation_receivedemail";',
                        'ALTER TABLE "marketing_email" RENAME TO "email_automation_email";',
                        'ALTER TABLE "marketing_emailattachment" RENAME TO "email_automation_emailattachment";',
                        'ALTER TABLE "marketing_email_companies" RENAME TO "email_automation_email_companies";',
                        'ALTER TABLE "marketing_email_contacts" RENAME TO "email_automation_email_contacts";',
                    ],
                ),
            ],
        ),
    ]
