# Generated by Django 4.2.25 on 2026-09-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0099_current_account_indexes'),
        ('marketing', '0082_drop_superseded_mail_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounting.currentaccount'),
        ),
    ]
