# Generated by Django 4.2.25 on 2026-09-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0083_current_account_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_quantity',
        ),
    ]
