# Generated by Django 4.2.25 on 2026-09-16 23:56

from collections import Counter

from django.db import migrations, models

# Frozen copies — a migration must not follow later edits to marketing/units.py.
PACK_FOR_UNIT = {"mt": "roll", "kg": "bale", "piece": "box", "pack": "box"}
UNIT_TO_STOREFRONT = {"mt": "mt", "kg": "kg", "piece": "units", "pack": "units"}
STOREFRONT_TO_UNIT = {"mt": "mt", "kg": "kg", "units": "piece"}


def seed_from_stock(apps, schema_editor):
    """Give every product the unit and pack its warehouse rows already say.

    Those rows agreed with each other for every product when this was
    written, so nothing is chosen between; if they ever don't, the most
    common answer wins. A product with no stock takes the unit its
    storefront field implies. Then the storefront field is derived from the
    unit, which corrects the ones that had drifted from the stock.
    """
    Product = apps.get_model("marketing", "Product")
    WarehouseProduct = apps.get_model("operating", "WarehouseProduct")

    seen = {}
    for pid, unit, pack in (WarehouseProduct.objects
                            .filter(catalog_variant__isnull=False)
                            .values_list("catalog_variant__product_id", "unit", "pack_type")):
        seen.setdefault(pid, Counter())[(unit, pack)] += 1

    products = list(Product.objects.only("id", "unit", "pack_type", "unit_of_measurement"))
    for p in products:
        if p.id in seen:
            p.unit, p.pack_type = seen[p.id].most_common(1)[0][0]
        else:
            p.unit = STOREFRONT_TO_UNIT.get(p.unit_of_measurement, "mt")
            p.pack_type = PACK_FOR_UNIT[p.unit]
        p.unit_of_measurement = UNIT_TO_STOREFRONT[p.unit]
    Product.objects.bulk_update(products, ["unit", "pack_type", "unit_of_measurement"],
                                batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0085_price_and_cost_not_negative'),
        # The warehouse rows still carry unit/pack_type at this point.
        ('operating', '0091_warehouse_costs_not_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_type',
            field=models.CharField(choices=[('roll', 'Roll'), ('box', 'Box'), ('bale', 'Bale'), ('bag', 'Bag'), ('bundle', 'Bundle'), ('pallet', 'Pallet')], default='roll', help_text='What one stock item of this product physically is', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('mt', 'Metre'), ('piece', 'Piece'), ('pack', 'Pack'), ('kg', 'Kilogram')], default='mt', help_text='What this product is counted in', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('units', 'Unit'), ('mt', 'Meter'), ('kg', 'Kilogram')], default='units', editable=False, null=True),
        ),
        # Reversing leaves the fields to be dropped; nothing to restore.
        migrations.RunPython(seed_from_stock, migrations.RunPython.noop),
    ]
