# Generated by Django 4.2.25 on 2026-09-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0086_product_owns_unit_and_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
