# Generated by Django 4.2.25 on 2026-09-17 11:44

from collections import Counter, defaultdict

from django.db import migrations, models


def seed_presets(apps, schema_editor):
    """Each group's preset is what its variants already carry: an attribute
    used by at least a fifth of the group's described variants, colour
    first, then the most used. Edited on the product group page after."""
    Category = apps.get_model("marketing", "ProductCategory")
    Preset = apps.get_model("marketing", "CategoryVariantAttribute")
    Variant = apps.get_model("marketing", "ProductVariant")
    Through = Variant.product_variant_attribute_values.through

    variants = defaultdict(set)
    uses = defaultdict(Counter)
    for category_id, variant_id, attribute_id in Through.objects.filter(
            productvariant__product__category__isnull=False).values_list(
            "productvariant__product__category_id", "productvariant_id",
            "productvariantattributevalue__product_variant_attribute_id"):
        variants[category_id].add(variant_id)
        uses[category_id][attribute_id] += 1

    Attribute = apps.get_model("marketing", "ProductVariantAttribute")
    names = dict(Attribute.objects.values_list("id", "name"))
    for category in Category.objects.all():
        total = len(variants[category.id])
        kept = [a for a, n in uses[category.id].items() if total and n / total >= 0.2]
        kept.sort(key=lambda a: (names[a] != "color", -uses[category.id][a], names[a]))
        Preset.objects.bulk_create([
            Preset(category=category, attribute_id=a, position=i) for i, a in enumerate(kept)
        ])

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0087_remove_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_presets', to='marketing.productvariantattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_presets', to='marketing.productcategory')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoryvariantattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='uniq_category_variant_attribute'),
        ),
        migrations.RunPython(seed_presets, migrations.RunPython.noop),
    ]
