# Generated by Django 4.2.25 on 2026-09-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0088_category_variant_attribute_presets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantattributevalue',
            options={'ordering': ['product_variant_attribute__name', 'product_variant_attribute_value']},
        ),
    ]
