# Generated by Django 4.2.25 on 2026-09-20 22:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0109_movement_type_fx_adjustment'),
        ('marketing', '0089_alter_productvariantattributevalue_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(db_index=True, help_text='Their article number, as printed on their invoice', max_length=64)),
                ('supplier_barcode', models.CharField(blank=True, db_index=True, help_text='Their PRODUCT-level barcode/GTIN, if they have one. Not a roll serial — those go on the stock item.', max_length=64, null=True)),
                ('supplier_description', models.CharField(blank=True, help_text='How the line reads on their invoice, for reconciliation', max_length=255)),
                ('supplier_unit', models.CharField(blank=True, help_text='The unit they sell in (box, yard, roll…). Blank = ours.', max_length=20)),
                ('qty_per_supplier_unit', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='How much of OUR unit one of THEIR units is', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('last_unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Their price per THEIR unit, when we last bought it', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_purchased_at', models.DateField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_preferred', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_account', models.ForeignKey(help_text='Who sells it to us — the account the purchase is billed to', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='accounting.currentaccount')),
                ('variant', models.ForeignKey(help_text='What it is in OUR catalog', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='marketing.productvariant')),
            ],
            options={
                'verbose_name': 'Supplier item',
                'verbose_name_plural': 'Supplier items',
                'ordering': ['-is_preferred', 'supplier_sku'],
                'indexes': [models.Index(fields=['variant', '-is_preferred'], name='marketing_s_variant_219a6a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('current_account', 'supplier_sku'), name='marketing_supplieritem_unique_sku_per_account'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('current_account', 'supplier_barcode'), name='marketing_supplieritem_unique_barcode_per_account'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('current_account', 'variant'), name='marketing_supplieritem_unique_variant_per_account'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.CheckConstraint(check=models.Q(('qty_per_supplier_unit__gt', 0)), name='marketing_supplieritem_qty_per_unit_positive'),
        ),
    ]
