# Generated by Django 4.2.25 on 2026-09-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0100_stockmovement_purpose'),
        ('marketing', '0091_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteItemRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='marketing.quoteitem')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_links', to='operating.warehouseproductitem')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
