# Generated by Django 4.2.25 on 2026-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0093_quote_internal_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogfile',
            options={'ordering': ['sequence', 'pk'], 'verbose_name': 'Blog file', 'verbose_name_plural': 'Blog files'},
        ),
        migrations.AlterField(
            model_name='blogfile',
            name='file_type',
            field=models.CharField(choices=[('cover', 'Cover image'), ('hero', 'Hero image'), ('content', 'Content image')], default='content', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category_tr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category (TR)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_tr',
            field=models.TextField(blank=True, verbose_name='Content (TR)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.URLField(blank=True, verbose_name='Cover image (list)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_tr',
            field=models.TextField(blank=True, verbose_name='Excerpt (TR)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.URLField(blank=True, verbose_name='Hero image (detail)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(blank=True, max_length=300, verbose_name='Title (TR)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('archive', 'Archive'), ('trash', 'Trash'), ('drafts', 'Drafts')], db_index=True, default='inbox', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_packaged',
            field=models.BooleanField(default=False, help_text='Is this product sold in packs? (of 12, of 5, etc.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Minimum order quantity — left blank, the product group's applies", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many pieces are in a pack? (required when is_packaged=True)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Margin % — left blank, the product group's applies", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(help_text='E.g. width, fabric type, intended use', max_length=255, verbose_name='Attribute name'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(help_text='E.g. 150cm, tulle, bridal', max_length=500, verbose_name='Attribute value'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated supply/delivery time (days)', null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='minimum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order quantity for products in this group (can be overridden per product)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margin % — added on top of cost (price = cost × (1 + margin/100))', max_digits=5, null=True),
        ),
    ]
