# Generated by Django 4.2.25 on 2026-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0095_loose_pack_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplieritem',
            name='marketing_supplieritem_unique_sku_per_account',
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='last_price_currency',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='supplier_sku',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Their article number, as printed on their invoice', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_sku', ''), _negated=True), fields=('current_account', 'supplier_sku'), name='marketing_supplieritem_unique_sku_per_account'),
        ),
    ]
