# Generated by Django 5.2.7 on 2026-05-15 11:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0065_alter_liabilityaccountspayable_supplier'),
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
    ]

    operations = [
        migrations.CreateModel(
            name='CariAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: CARI-001', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('customer', 'Müşteri'), ('supplier', 'Tedarikçi'), ('both', 'Müşteri & Tedarikçi'), ('staff', 'Personel'), ('other', 'Diğer')], default='customer', max_length=20)),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, help_text='VKN', max_length=11)),
                ('identity_number', models.CharField(blank=True, help_text='TCKN', max_length=11)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_country', models.CharField(default='TR', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('payment_term_days', models.PositiveIntegerField(default=30, help_text='Vade (gün)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Müşteriye özel iskonto %', max_digits=5)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('cached_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cached_balance_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_accounts', to='accounting.book')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_accounts', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_accounts', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cari_accounts', to='authentication.member')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cari_accounts', to='accounting.currencycategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cari_accounts', to='crm.supplier')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
            },
        ),
        migrations.CreateModel(
            name='CariMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14)),
                ('amount_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('movement_type', models.CharField(choices=[('opening', 'Açılış Bakiyesi'), ('invoice_sale', 'Satış Faturası'), ('invoice_purchase', 'Alış Faturası'), ('return_sale', 'Satış İadesi'), ('return_purchase', 'Alış İadesi'), ('collection', 'Tahsilat'), ('payment', 'Ödeme'), ('advance_in', 'Alınan Avans'), ('advance_out', 'Verilen Avans'), ('interest', 'Vade Farkı / Faiz'), ('discount', 'İskonto'), ('adjustment', 'Mahsup / Düzeltme'), ('check_in', 'Çek/Senet Alındı'), ('check_out', 'Çek/Senet Verildi'), ('legacy_ar', 'Eski Sistem - Alacak'), ('legacy_ap', 'Eski Sistem - Borç')], max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('legacy_ar_id', models.PositiveIntegerField(blank=True, null=True)),
                ('legacy_ap_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_movements', to='accounting.book')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='current_account.cariaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cari_movements', to='authentication.member')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currencycategory')),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Cari Hareketi',
                'verbose_name_plural': 'Cari Hareketleri',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CariSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_cari_seq', models.PositiveIntegerField(default=1)),
                ('next_invoice_seq', models.PositiveIntegerField(default=1)),
                ('next_payment_seq', models.PositiveIntegerField(default=1)),
                ('cari_code_prefix', models.CharField(default='CARI', max_length=10)),
                ('cari_code_padding', models.PositiveSmallIntegerField(default=3)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('default_payment_term_days', models.PositiveIntegerField(default=30)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cari_settings', to='accounting.book')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_settings_default', to='accounting.currencycategory')),
            ],
            options={
                'verbose_name': 'Cari Ayarları',
                'verbose_name_plural': 'Cari Ayarları',
            },
        ),
        migrations.AddIndex(
            model_name='cariaccount',
            index=models.Index(fields=['book', 'is_active'], name='current_acc_book_id_589db5_idx'),
        ),
        migrations.AddIndex(
            model_name='cariaccount',
            index=models.Index(fields=['book', 'type'], name='current_acc_book_id_eea43a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cariaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('book', 'contact'), name='uniq_cari_book_contact'),
        ),
        migrations.AddConstraint(
            model_name='cariaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('book', 'company'), name='uniq_cari_book_company'),
        ),
        migrations.AddConstraint(
            model_name='cariaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('book', 'supplier'), name='uniq_cari_book_supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='cariaccount',
            unique_together={('book', 'code')},
        ),
        migrations.AddIndex(
            model_name='carimovement',
            index=models.Index(fields=['cari', '-date'], name='current_acc_cari_id_5398aa_idx'),
        ),
        migrations.AddIndex(
            model_name='carimovement',
            index=models.Index(fields=['book', 'due_date'], name='current_acc_book_id_f9b184_idx'),
        ),
        migrations.AddIndex(
            model_name='carimovement',
            index=models.Index(fields=['movement_type'], name='current_acc_movemen_448bcf_idx'),
        ),
    ]
