# Generated by Django 5.2.7 on 2026-05-15 11:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_alter_liabilityaccountspayable_supplier'),
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
        ('current_account', '0002_backfill_from_legacy_ar_ap'),
        ('marketing', '0071_rename_websubscription_and_english_verbose'),
        ('operating', '0043_warehouse_accounting_book_warehouse_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='FAT', max_length=10)),
                ('number', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('sales', 'Satış Faturası'), ('purchase', 'Alış Faturası'), ('sales_return', 'Satış İadesi'), ('purchase_return', 'Alış İadesi'), ('proforma', 'Proforma')], default='sales', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('issued', 'Kesildi'), ('partially_paid', 'Kısmi Ödendi'), ('paid', 'Ödendi'), ('overdue', 'Vadesi Geçti'), ('cancelled', 'İptal')], default='draft', max_length=20)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('earsiv_uuid', models.CharField(blank=True, max_length=50)),
                ('earsiv_status', models.CharField(blank=True, max_length=20)),
                ('earsiv_pdf_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.book')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='current_account.cariaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to='authentication.member')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currencycategory')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operating.order')),
                ('posted_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='current_account.carimovement')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit', models.CharField(default='adet', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='KDV hariç birim fiyat', max_digits=14)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% iskonto', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='KDV %', max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='current_account.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='marketing.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='marketing.productvariant')),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
                'ordering': ['invoice', 'line_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['book', '-date'], name='current_acc_book_id_a42db7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['cari', '-date'], name='current_acc_cari_id_0f5065_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='current_acc_status_3547ee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='current_acc_due_dat_af1360_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('book', 'series', 'number')},
        ),
    ]
