# Generated by Django 5.2.7 on 2026-05-15 11:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_alter_liabilityaccountspayable_supplier'),
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
        ('current_account', '0003_invoice_invoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('collection', 'Tahsilat (müşteriden)'), ('payment', 'Ödeme (tedarikçiye)'), ('refund_in', 'Müşteriye İade (bizden)'), ('refund_out', 'Tedarikçiden İade (bize)')], default='collection', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Nakit'), ('bank_transfer', 'Banka Havalesi/EFT'), ('credit_card', 'Kredi Kartı (POS)'), ('check', 'Çek'), ('promissory_note', 'Senet'), ('offset', 'Mahsup'), ('other', 'Diğer')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal')], default='draft', max_length=20)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive — sign comes from `type`', max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.book')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='current_account.cariaccount')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cari_payments', to='accounting.cashaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to='authentication.member')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currencycategory')),
                ('posted_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='current_account.carimovement')),
            ],
            options={
                'verbose_name': 'Tahsilat / Ödeme',
                'verbose_name_plural': 'Tahsilatlar / Ödemeler',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive — the portion of the payment applied here.', max_digits=14)),
                ('invoice', models.ForeignKey(blank=True, help_text='Boş bırakılırsa cari avans olarak kalır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='current_account.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='current_account.payment')),
            ],
            options={
                'verbose_name': 'Ödeme Eşleştirmesi',
                'verbose_name_plural': 'Ödeme Eşleştirmeleri',
                'ordering': ['payment', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['book', '-date'], name='current_acc_book_id_6e27a9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['cari', '-date'], name='current_acc_cari_id_2544e0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='current_acc_status_ad4fa1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('book', 'number')},
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice'], name='current_acc_invoice_7a6134_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='current_acc_payment_07bd76_idx'),
        ),
    ]
