# Generated by Django 5.2.7 on 2026-05-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_alter_liabilityaccountspayable_supplier'),
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
        ('current_account', '0004_payment_paymentallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrPromissoryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('check', 'Çek'), ('promissory_note', 'Senet')], default='check', max_length=20)),
                ('direction', models.CharField(choices=[('received', 'Müşteriden Alınan'), ('given', 'Tedarikçiye Verilen')], default='received', max_length=10)),
                ('status', models.CharField(choices=[('portfolio', 'Portföyde'), ('endorsed', 'Ciro Edildi'), ('deposited', 'Bankaya Verildi'), ('cleared', 'Tahsil Edildi'), ('bounced', 'Karşılıksız'), ('returned', 'İade Edildi'), ('cancelled', 'İptal')], default='portfolio', max_length=20)),
                ('serial_no', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, help_text='Banka adı (çek)', max_length=100)),
                ('branch', models.CharField(blank=True, help_text='Şube (çek)', max_length=100)),
                ('account_no', models.CharField(blank=True, max_length=50)),
                ('drawer', models.CharField(blank=True, help_text='Keşideci adı', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='accounting.book')),
                ('cari', models.ForeignKey(help_text='Çeki veren / alan cari', on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='current_account.cariaccount')),
                ('cleared_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_checks', to='accounting.cashaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checks', to='authentication.member')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currencycategory')),
                ('endorse_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_endorsement', to='current_account.carimovement')),
                ('endorsed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endorsed_checks', to='current_account.cariaccount')),
                ('posted_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_initial', to='current_account.carimovement')),
            ],
            options={
                'verbose_name': 'Çek / Senet',
                'verbose_name_plural': 'Çekler / Senetler',
                'ordering': ['-due_date', '-id'],
                'indexes': [models.Index(fields=['book', 'status'], name='current_acc_book_id_7a0b5c_idx'), models.Index(fields=['cari', '-due_date'], name='current_acc_cari_id_d7438e_idx'), models.Index(fields=['due_date'], name='current_acc_due_dat_fa797e_idx')],
            },
        ),
    ]
