# Generated by Django 5.2.7 on 2026-05-15 13:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0005_checkorpromissorynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cariaccount',
            options={'verbose_name': 'Current Account', 'verbose_name_plural': 'Current Accounts'},
        ),
        migrations.AlterModelOptions(
            name='carimovement',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Account Movement', 'verbose_name_plural': 'Account Movements'},
        ),
        migrations.AlterModelOptions(
            name='carisettings',
            options={'verbose_name': 'Account Settings', 'verbose_name_plural': 'Account Settings'},
        ),
        migrations.AlterModelOptions(
            name='checkorpromissorynote',
            options={'ordering': ['-due_date', '-id'], 'verbose_name': 'Check / Promissory Note', 'verbose_name_plural': 'Checks / Promissory Notes'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['invoice', 'line_no', 'id'], 'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Collection / Payment', 'verbose_name_plural': 'Collections / Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'ordering': ['payment', 'id'], 'verbose_name': 'Payment Allocation', 'verbose_name_plural': 'Payment Allocations'},
        ),
        migrations.AlterField(
            model_name='cariaccount',
            name='code',
            field=models.CharField(help_text='e.g., CARI-001', max_length=20),
        ),
        migrations.AlterField(
            model_name='cariaccount',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer-specific discount %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='cariaccount',
            name='identity_number',
            field=models.CharField(blank=True, help_text='ID Number (TCKN)', max_length=11),
        ),
        migrations.AlterField(
            model_name='cariaccount',
            name='payment_term_days',
            field=models.PositiveIntegerField(default=30, help_text='Payment term (days)'),
        ),
        migrations.AlterField(
            model_name='cariaccount',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax Number (VKN)', max_length=11),
        ),
        migrations.AlterField(
            model_name='cariaccount',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer & Supplier'), ('staff', 'Staff'), ('other', 'Other')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='carimovement',
            name='amount_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount normalized to base currency (USD)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='carimovement',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate from movement currency to base (USD)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='carimovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('invoice_sale', 'Sales Invoice'), ('invoice_purchase', 'Purchase Invoice'), ('return_sale', 'Sales Return'), ('return_purchase', 'Purchase Return'), ('collection', 'Collection'), ('payment', 'Payment'), ('advance_in', 'Advance Received'), ('advance_out', 'Advance Given'), ('interest', 'Interest / Late Fee'), ('discount', 'Discount'), ('adjustment', 'Offset / Adjustment'), ('check_in', 'Check/Note Received'), ('check_out', 'Check/Note Given'), ('legacy_ar', 'Legacy - Receivable'), ('legacy_ap', 'Legacy - Payable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carimovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Invoice no, check no, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='bank',
            field=models.CharField(blank=True, help_text='Bank name (for check)', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch (for check)', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='cari',
            field=models.ForeignKey(help_text='Account that gave or received the instrument', on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='current_account.cariaccount'),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='direction',
            field=models.CharField(choices=[('received', 'Received from Customer'), ('given', 'Given to Supplier')], default='received', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='drawer',
            field=models.CharField(blank=True, help_text='Drawer name', max_length=200),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='instrument',
            field=models.CharField(choices=[('check', 'Check'), ('promissory_note', 'Promissory Note')], default='check', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkorpromissorynote',
            name='status',
            field=models.CharField(choices=[('portfolio', 'In Portfolio'), ('endorsed', 'Endorsed'), ('deposited', 'Deposited to Bank'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='portfolio', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales Invoice'), ('purchase', 'Purchase Invoice'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('proforma', 'Proforma')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='VAT %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price excluding VAT', max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer / EFT'), ('credit_card', 'Credit Card (POS)'), ('check', 'Check'), ('promissory_note', 'Promissory Note'), ('offset', 'Offset'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('collection', 'Collection (from customer)'), ('payment', 'Payment (to supplier)'), ('refund_in', 'Refund to Customer'), ('refund_out', 'Refund from Supplier')], default='collection', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Leave empty to keep as account advance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='current_account.invoice'),
        ),
    ]
