# Generated by Django 5.2.7 on 2026-05-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0006_alter_cariaccount_options_alter_carimovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('order_sale', 'Sales Order'), ('invoice_sale', 'Sales Invoice'), ('invoice_purchase', 'Purchase Invoice'), ('return_sale', 'Sales Return'), ('return_purchase', 'Purchase Return'), ('collection', 'Collection'), ('payment', 'Payment'), ('advance_in', 'Advance Received'), ('advance_out', 'Advance Given'), ('interest', 'Interest / Late Fee'), ('discount', 'Discount'), ('adjustment', 'Offset / Adjustment'), ('check_in', 'Check/Note Received'), ('check_out', 'Check/Note Given'), ('legacy_ar', 'Legacy - Receivable'), ('legacy_ap', 'Legacy - Payable')], max_length=20),
        ),
    ]
