# Generated by Django 5.2.7 on 2026-07-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0008_invoice_bill_to_address_invoice_bill_to_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='series',
            field=models.CharField(default='INV', max_length=10),
        ),
    ]
