# Generated by Django 4.2.25 on 2026-07-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0058_warehouseproductroll_purchase_invoice_item'),
        ('current_account', '0009_alter_invoice_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='operating.orderitem'),
        ),
    ]
