# Generated by Django 5.2.7 on 2026-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0010_invoiceitem_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='carisettings',
            name='invoice_language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], default='en', max_length=5),
        ),
    ]
