# Generated by Django 4.2.25 on 2026-08-11 23:35

from django.db import migrations


class Migration(migrations.Migration):
    """Release the cari models — state only.

    accounting/0066 renamed the physical tables and took ownership of them.
    These DeleteModel operations must therefore touch state ONLY; letting them
    reach the database would drop the tables that migration just adopted.

    The app itself stays installed as a migrations-only stub, because migrations
    in `operating` depend on ('current_account', ...) and the graph has to keep
    resolving on databases that already applied them.
    """


    dependencies = [
        ('operating', '0068_alter_order_cari_and_more'),
        ('current_account', '0011_carisettings_invoice_language'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='carimovement',
                    name='book',
                ),
                migrations.RemoveField(
                    model_name='carimovement',
                    name='cari',
                ),
                migrations.RemoveField(
                    model_name='carimovement',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='carimovement',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='carimovement',
                    name='source_type',
                ),
                migrations.RemoveField(
                    model_name='carisettings',
                    name='book',
                ),
                migrations.RemoveField(
                    model_name='carisettings',
                    name='default_currency',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='book',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='cari',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='cleared_cash_account',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='endorse_movement',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='endorsed_to',
                ),
                migrations.RemoveField(
                    model_name='checkorpromissorynote',
                    name='posted_movement',
                ),
                migrations.AlterUniqueTogether(
                    name='invoice',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='book',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='cari',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='order',
                ),
                migrations.RemoveField(
                    model_name='invoice',
                    name='posted_movement',
                ),
                migrations.RemoveField(
                    model_name='invoiceitem',
                    name='invoice',
                ),
                migrations.RemoveField(
                    model_name='invoiceitem',
                    name='order_item',
                ),
                migrations.RemoveField(
                    model_name='invoiceitem',
                    name='product',
                ),
                migrations.RemoveField(
                    model_name='invoiceitem',
                    name='variant',
                ),
                migrations.AlterUniqueTogether(
                    name='payment',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='book',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='cari',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='cash_account',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='currency',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='posted_movement',
                ),
                migrations.RemoveField(
                    model_name='paymentallocation',
                    name='invoice',
                ),
                migrations.RemoveField(
                    model_name='paymentallocation',
                    name='payment',
                ),
                migrations.DeleteModel(
                    name='CariAccount',
                ),
                migrations.DeleteModel(
                    name='CariMovement',
                ),
                migrations.DeleteModel(
                    name='CariSettings',
                ),
                migrations.DeleteModel(
                    name='CheckOrPromissoryNote',
                ),
                migrations.DeleteModel(
                    name='Invoice',
                ),
                migrations.DeleteModel(
                    name='InvoiceItem',
                ),
                migrations.DeleteModel(
                    name='Payment',
                ),
                migrations.DeleteModel(
                    name='PaymentAllocation',
                ),
            ],
            database_operations=[],
        ),
    ]
