# Generated by Django 4.2.4 on 2025-03-07 21:19

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_shares', models.PositiveIntegerField(default=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
            ],
            options={
                'verbose_name_plural': 'Cash Accounts',
            },
        ),
        migrations.CreateModel(
            name='CurrencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currency Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('type_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_out', models.DecimalField(decimal_places=2, max_digits=12)),
                ('burn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accounts_receivable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accounts_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('runway', models.DecimalField(decimal_places=1, max_digits=12)),
                ('growth_rate', models.DecimalField(decimal_places=1, max_digits=12)),
                ('default_alive', models.BooleanField(default=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
            ],
        ),
        migrations.CreateModel(
            name='LiabilityAccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receipt', models.CharField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier')),
            ],
            options={
                'verbose_name_plural': 'Liability Accounts Payables',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_cate', models.DateTimeField(default=accounting.models.default_due_date)),
                ('items', models.JSONField(default=accounting.models.invoice_items_default, verbose_name='ItemsInfo')),
                ('invoice_type', models.CharField(choices=[('proforma', 'Proforma'), ('commercial', 'Commercial')], default='proforma')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
            ],
        ),
        migrations.CreateModel(
            name='InTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='accounting.cashaccount')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='accounting.cashaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EquityRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('revenue_type', models.CharField(choices=[('sales', 'Sales'), ('other', 'Other')], default='sales')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Equity Revenues',
            },
        ),
        migrations.CreateModel(
            name='EquityExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.expensecategory')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Equity Expenses',
            },
        ),
        migrations.CreateModel(
            name='EquityDivident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
            options={
                'verbose_name_plural': 'Equity Dividents',
            },
        ),
        migrations.CreateModel(
            name='EquityCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_invested', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_shares_issued', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
            options={
                'verbose_name_plural': 'Equity Capitals',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('from_cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange_source', to='accounting.cashaccount')),
                ('to_cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange_destination', to='accounting.cashaccount')),
            ],
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
        migrations.CreateModel(
            name='AssetInventoryRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('stock_id', models.CharField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, choices=[('units', 'Unit'), ('mt', 'Meter'), ('kg', 'Kilogram')], default=('units', 'Unit'), null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('warehouse', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('raw_type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default=('direct', 'Direct'))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier')),
            ],
            options={
                'verbose_name_plural': 'Asset Inventory Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='AssetInventoryGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_type', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wip', 'Work in Progress'), ('finished', 'Finished Good')])),
                ('warehouse', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Inventory Goods',
            },
        ),
        migrations.CreateModel(
            name='AssetCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transaction')),
            ],
            options={
                'verbose_name_plural': 'Asset Cash',
            },
        ),
        migrations.CreateModel(
            name='AssetAccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice')),
            ],
            options={
                'verbose_name_plural': 'Asset Accounts Receivables',
            },
        ),
        migrations.CreateModel(
            name='StakeholderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
            options={
                'verbose_name_plural': 'Stakeholder Books',
                'unique_together': {('member', 'book')},
            },
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('book', 'name'), name='unique_book_cashaccount'),
        ),
        migrations.AddConstraint(
            model_name='assetinventoryrawmaterial',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='unique_name_supplier'),
        ),
    ]
