# Generated by Django 4.2.4 on 2024-10-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencycategory',
            name='symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
