# Generated by Django 4.2.4 on 2025-07-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_name'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='crm.company'),
        ),
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='crm.contact'),
        ),
    ]
