# Generated by Django 4.2.4 on 2025-07-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0013_alter_orderitem_quantity'),
        ('accounting', '0002_alter_assetaccountsreceivable_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operating.order'),
        ),
    ]
