# Generated by Django 4.2.4 on 2024-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_currencycategory_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
