# Generated by Django 4.2.4 on 2025-07-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_invoice_id_alter_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice'),
            preserve_default=False,
        ),
    ]
