# Generated by Django 4.2.4 on 2024-10-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_book_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashCategory',
            new_name='CashAccouns',
        ),
        migrations.AlterModelOptions(
            name='cashaccouns',
            options={'verbose_name_plural': 'Cash Accounts'},
        ),
        migrations.RemoveField(
            model_name='equity',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='date_invested',
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='books',
            field=models.ManyToManyField(related_name='stakeholders', to='accounting.book'),
        ),
        migrations.CreateModel(
            name='Equity_Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('date_invested', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.stakeholder')),
            ],
        ),
    ]
