# Generated by Django 4.2.4 on 2024-07-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_category_alter_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='note',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='note',
            new_name='description',
        ),
    ]
