# Generated by Django 4.2.4 on 2025-07-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_assetaccountsreceivable_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_cate',
            new_name='due_date',
        ),
    ]
