# Generated by Django 4.2.4 on 2024-10-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_rename_cashaccouns_cashaccounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashAccounts',
            new_name='CashAccount',
        ),
        migrations.AddField(
            model_name='equity_capital',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
    ]
