# Generated by Django 4.2.4 on 2024-09-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_asset_created_at_book_created_at_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
        migrations.AddField(
            model_name='sale',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
    ]
