# Generated by Django 4.2.4 on 2024-10-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_rename_cashaccounts_cashaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('date_invested', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Equity Capitals',
            },
        ),
        migrations.DeleteModel(
            name='Equity_Capital',
        ),
    ]
