# Generated by Django 4.2.4 on 2025-07-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_rename_due_cate_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounting.currencycategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('proforma', 'Proforma'), ('commercial', 'Commercial')], default='proforma', max_length=20),
        ),
    ]
