# Generated by Django 4.2.4 on 2024-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_equitycapital_delete_equity_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
