# Generated by Django 4.2.4 on 2025-07-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_invoice_currency_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
