# Generated by Django 4.2.4 on 2024-10-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_cashaccount_balance_alter_cashaccount_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='EquityExpense',
        ),
        migrations.DeleteModel(
            name='Equity',
        ),
    ]
