# Generated by Django 4.2.4 on 2025-08-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0021_warehouse'),
        ('accounting', '0009_alter_assetaccountsreceivable_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='location',
        ),
        migrations.AlterField(
            model_name='assetinventoryrawmaterial',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operating.warehouse'),
        ),
    ]
