# Generated by Django 4.2.4 on 2024-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_asset_book_alter_sale_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_in_months',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
