# Generated by Django 4.2.4 on 2024-10-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_rename_expense_equityexpense_delete_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityexpense',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
    ]
