# Generated by Django 4.2.4 on 2025-08-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_assetinventoryrawmaterial_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinventoryrawmaterial',
            old_name='stock_id',
            new_name='sku',
        ),
    ]
