# Generated by Django 4.2.4 on 2024-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_asset_residual_value_asset_useful_life_in_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='depreciating',
            field=models.BooleanField(default=False),
        ),
    ]
