# Generated by Django 4.2.4 on 2025-08-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_rename_stock_id_assetinventoryrawmaterial_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinventoryrawmaterial',
            old_name='receipt_number',
            new_name='supplier_sku',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='book',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
