# Generated by Django 4.2.4 on 2024-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_equityexpense_cash_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityexpense',
            name='cash_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
            preserve_default=False,
        ),
    ]
