# Generated by Django 4.2.4 on 2025-08-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_rename_receipt_number_assetinventoryrawmaterial_supplier_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
            preserve_default=False,
        ),
    ]
