# Generated by Django 4.2.4 on 2025-08-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_assetinventoryrawmaterial_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventoryFinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_type', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('wip', 'Work in Progress'), ('finished', 'Finished Good')])),
                ('warehouse', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Inventory Goods',
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.assetinventoryrawmaterial')),
            ],
        ),
        migrations.DeleteModel(
            name='AssetInventoryGood',
        ),
    ]
