# Generated by Django 4.2.4 on 2024-09-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_asset_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
