# Generated by Django 4.2.4 on 2024-10-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_equityexpense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='share',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
