# Generated by Django 4.2.4 on 2025-08-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_goodsreceipt_goodsreceiptitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='receipt_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
