# Generated by Django 4.2.4 on 2024-11-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_stakeholder_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
