# Generated by Django 4.2.4 on 2025-08-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_name'),
        ('accounting', '0016_goodsreceipt_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawGoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='GoodsReceipt',
            new_name='RawGoodsReceipt',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptItem',
        ),
        migrations.AddField(
            model_name='rawgoodsreceiptitem',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.rawgoodsreceipt'),
        ),
        migrations.AddField(
            model_name='rawgoodsreceiptitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounting.assetinventoryrawmaterial'),
        ),
    ]
