# Generated by Django 4.2.4 on 2024-09-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_rename_bankaccounts_cashaccounts_capital'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashAccounts',
            new_name='CashCategory',
        ),
    ]
