# Generated by Django 4.2.4 on 2024-11-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_equityexpense_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityexpense',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
