# Generated by Django 4.2.4 on 2025-08-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_name'),
        ('accounting', '0017_rawgoodsreceiptitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_number', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('finished_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounting.assetinventoryfinishedgood')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.finishedgoodsreceipt')),
            ],
        ),
    ]
