# Generated by Django 4.2.4 on 2024-09-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_rename_cashaccounts_cashcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashcategory',
            name='balance',
        ),
    ]
