# Generated by Django 4.2.4 on 2025-08-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_finishedgoodsreceipt_finishedgoodsreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finishedgoodsreceipt',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
        migrations.AddField(
            model_name='finishedgoodsreceiptitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rawgoodsreceipt',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawgoodsreceipt',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
        migrations.AddField(
            model_name='rawgoodsreceiptitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
