# Generated by Django 4.2.4 on 2024-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_remove_cashcategory_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcategory',
            name='name',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
