# Generated by Django 4.2.4 on 2025-08-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_finishedgoodsreceipt_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedgoodsreceipt',
            old_name='paid',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='rawgoodsreceipt',
            old_name='paid',
            new_name='payment_status',
        ),
    ]
