# Generated by Django 4.2.4 on 2024-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_equityrevenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equityrevenue',
            options={'verbose_name_plural': 'Equity Revenues'},
        ),
        migrations.AddField(
            model_name='equityrevenue',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
