# Generated by Django 4.2.4 on 2025-08-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_rename_paid_finishedgoodsreceipt_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedgoodsreceipt',
            old_name='payment_type',
            new_name='cash_account',
        ),
        migrations.RenameField(
            model_name='rawgoodsreceipt',
            old_name='payment_type',
            new_name='cash_account',
        ),
    ]
