# Generated by Django 4.2.4 on 2024-09-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_cashcategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashcategory',
            options={'verbose_name_plural': 'Cash Categories'},
        ),
        migrations.AddField(
            model_name='capital',
            name='TargetAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashcategory'),
        ),
    ]
