# Generated by Django 4.2.4 on 2025-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_rename_payment_type_finishedgoodsreceipt_cash_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
