# Generated by Django 4.2.4 on 2024-09-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_cashcategory_options_capital_targetaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capital',
            old_name='TargetAccount',
            new_name='CashCategory',
        ),
    ]
