# Generated by Django 4.2.4 on 2024-09-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_rename_targetaccount_capital_cashcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcategory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
