# Generated by Django 4.2.4 on 2025-08-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_assetinventoryrawmaterial_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventoryfinishedgood',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='quantity',
        ),
    ]
