# Generated by Django 4.2.4 on 2025-08-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_remove_assetinventoryfinishedgood_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedgoodsreceiptitem',
            old_name='cost',
            new_name='unit_cost',
        ),
        migrations.RenameField(
            model_name='rawgoodsreceiptitem',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
