# Generated by Django 4.2.4 on 2024-11-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_equitydivident'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitydivident',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.stakeholder'),
        ),
    ]
