# Generated by Django 4.2.4 on 2024-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_equitydivident_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.JSONField(default={}),
        ),
    ]
