# Generated by Django 4.2.4 on 2025-08-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_name'),
        ('accounting', '0024_rename_cost_finishedgoodsreceiptitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountsreceivable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='crm.supplier'),
        ),
    ]
