# Generated by Django 4.2.4 on 2024-10-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_capital_created_at_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholder',
            old_name='shares',
            new_name='share',
        ),
    ]
