# Generated by Django 4.2.4 on 2025-08-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_assetaccountsreceivable_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type_pk',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('dividend', 'Dividend'), ('inTransfer', 'In Transfer')], max_length=50, null=True),
        ),
    ]
