# Generated by Django 4.2.4 on 2024-11-30 17:53

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_sale_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.JSONField(default=accounting.models.invoice_default),
        ),
    ]
