# Generated by Django 4.2.4 on 2024-10-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_remove_stakeholder_book_stakeholder_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='book',
            field=models.ManyToManyField(related_name='Books', to='accounting.book'),
        ),
    ]
