# Generated by Django 4.2.4 on 2024-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_alter_sale_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
    ]
