# Generated by Django 4.2.4 on 2025-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('dividend', 'Dividend'), ('purchase', 'Purchase'), ('in_transfer', 'In Transfer')], max_length=50, null=True),
        ),
    ]
