# Generated by Django 4.2.4 on 2024-11-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_remove_sale_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
