# Generated by Django 4.2.4 on 2025-08-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilityaccountspayable',
            name='receipt',
        ),
        migrations.AddField(
            model_name='liabilityaccountspayable',
            name='finished_goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.finishedgoodsreceipt'),
        ),
        migrations.AddField(
            model_name='liabilityaccountspayable',
            name='raw_goods_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.rawgoodsreceipt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liabilityaccountspayable',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
