# Generated by Django 4.2.4 on 2025-08-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_remove_liabilityaccountspayable_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
