# Generated by Django 4.2.4 on 2024-11-30 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_invoice_invoiceitem_alter_cashaccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 19, 41, 46, 869162, tzinfo=datetime.timezone.utc)),
        ),
    ]
