# Generated by Django 4.2.4 on 2024-10-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_alter_capital_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='share',
        ),
    ]
