# Generated by Django 4.2.4 on 2025-08-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaccountsreceivable',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
