# Generated by Django 4.2.4 on 2025-08-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_remove_assetaccountsreceivable_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='accounting.book'),
        ),
    ]
