# Generated by Django 4.2.4 on 2025-08-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_stakeholderbook_book'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetcash',
            unique_together={('book', 'currency')},
        ),
    ]
