# Generated by Django 4.2.4 on 2024-11-30 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 30, 21, 2, 50, 417260, tzinfo=datetime.timezone.utc)),
        ),
    ]
