# Generated by Django 4.2.4 on 2025-08-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_alter_assetcash_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcash',
            old_name='currency_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='assetcash',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='assetcash',
            name='transaction',
        ),
    ]
