# Generated by Django 4.2.4 on 2025-01-24 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 23, 18, 58, 45, 302508, tzinfo=datetime.timezone.utc)),
        ),
    ]
