# Generated by Django 4.2.4 on 2025-08-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_rename_currency_balance_assetcash_balance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionEntry',
        ),
    ]
