# Generated by Django 4.2.4 on 2025-08-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_rename_transaction_transactionentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionentry',
            old_name='value',
            new_name='amount',
        ),
    ]
