# Generated by Django 4.2.4 on 2025-01-25 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityrevenue',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 24, 7, 35, 52, 475257, tzinfo=datetime.timezone.utc)),
        ),
    ]
