# Generated by Django 4.2.4 on 2025-08-11 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounting', '0036_rename_value_transactionentry_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_base_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Cash Transaction Entries',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='TransactionEntry',
        ),
    ]
