# Generated by Django 4.2.4 on 2025-08-11 07:44

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounting', '0037_cashtransactionentry_currencyexchangerate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransactionentry',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=accounting.models.allowed_equity_models, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashtransactionentry',
            name='equity_pk',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
