# Generated by Django 4.2.4 on 2025-08-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_alter_cashtransactionentry_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransactionentry',
            name='total_base_currency_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
