# Generated by Django 4.2.4 on 2025-08-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0021_warehouse'),
        ('accounting', '0039_cashtransactionentry_total_base_currency_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equityrevenue',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='equityrevenue',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operating.order'),
        ),
    ]
