# Generated by Django 4.2.4 on 2025-01-31 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_remove_equityexpense_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 12, 14, 5, 126004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='InTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='accounting.cashaccount')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='accounting.cashaccount')),
            ],
        ),
    ]
