# Generated by Django 4.2.4 on 2025-08-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_remove_equityrevenue_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtransactionentry',
            old_name='equity_pk',
            new_name='content_pk',
        ),
    ]
