# Generated by Django 4.2.4 on 2025-08-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_rename_equity_pk_cashtransactionentry_content_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intransfer',
            old_name='source',
            new_name='from_cash_account',
        ),
        migrations.RenameField(
            model_name='intransfer',
            old_name='destination',
            new_name='to_cash_account',
        ),
    ]
