# Generated by Django 4.2.4 on 2025-08-13 07:08

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_rename_source_intransfer_from_cash_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransfer',
            name='currency',
            field=models.ForeignKey(default=accounting.models.get_base_currency, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
