# Generated by Django 4.2.4 on 2025-02-07 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_alter_invoice_due_date_accountbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 14, 18, 2, 78463, tzinfo=datetime.timezone.utc)),
        ),
    ]
