# Generated by Django 4.2.4 on 2025-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_alter_intransfer_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashtransactionentry',
            old_name='amount_base_currency',
            new_name='amount_in_base_currency',
        ),
        migrations.AddField(
            model_name='cashtransactionentry',
            name='is_amount_positive',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
