# Generated by Django 4.2.4 on 2025-02-07 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_transaction_total_balance_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_balance',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 14, 58, 40, 564471, tzinfo=datetime.timezone.utc)),
        ),
    ]
