# Generated by Django 4.2.4 on 2025-08-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_rename_amount_base_currency_cashtransactionentry_amount_in_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventoryRawMaterialGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
