# Generated by Django 4.2.4 on 2025-02-07 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_remove_transaction_total_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 17, 2, 16, 633146, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('money_out', models.DecimalField(decimal_places=2, max_digits=12)),
                ('burn', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accounts_receivable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accounts_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('runway', models.DecimalField(decimal_places=1, max_digits=12)),
                ('growth_rate', models.DecimalField(decimal_places=1, max_digits=12)),
                ('default_alive', models.BooleanField(default=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
            ],
        ),
    ]
