# Generated by Django 4.2.4 on 2025-02-07 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_alter_invoice_due_date_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='share',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 19, 3, 9, 180010, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='StakeholderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.stakeholder')),
            ],
            options={
                'unique_together': {('stakeholder', 'book')},
            },
        ),
    ]
