# Generated by Django 4.2.4 on 2025-08-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('operating', '0023_remove_finishedgood_book_finishedgood_order_and_more'),
        ('crm', '0012_alter_company_name'),
        ('accounting', '0045_assetinventoryrawmaterialgood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawGoodsReceipt',
            new_name='RawMaterialGoodsReceipt',
        ),
        migrations.DeleteModel(
            name='AssetInventoryRawMaterialGood',
        ),
        migrations.RemoveField(
            model_name='rawgoodsreceiptitem',
            name='goods_receipt',
        ),
        migrations.RemoveField(
            model_name='rawgoodsreceiptitem',
            name='raw_material',
        ),
        migrations.AlterModelOptions(
            name='assetinventoryrawmaterial',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='assetinventoryrawmaterial',
            name='unique_name_supplier',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='raw_type',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='supplier_sku',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='unit_of_measurement',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='assetinventoryrawmaterial',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterialgoodsreceipt',
            constraint=models.UniqueConstraint(fields=('supplier', 'receipt_number'), name='unique_supplier_receipt_number'),
        ),
        migrations.DeleteModel(
            name='RawGoodsReceiptItem',
        ),
    ]
