# Generated by Django 4.2.4 on 2025-08-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_rename_rawgoodsreceipt_rawmaterialgoodsreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RawMaterialGoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.assetinventoryrawmaterial')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.rawmaterialgoodsreceipt')),
            ],
        ),
    ]
