# Generated by Django 4.2.4 on 2025-02-07 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_remove_stakeholder_share_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 19, 22, 24, 785276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='books',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
    ]
