# Generated by Django 4.2.4 on 2025-02-07 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_alter_invoice_due_date_remove_stakeholder_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='books',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 19, 46, 49, 80007, tzinfo=datetime.timezone.utc)),
        ),
    ]
