# Generated by Django 4.2.4 on 2025-08-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0025_remove_rawmaterialgooditem_raw_material_goods_receipt_item'),
        ('accounting', '0047_assetinventoryrawmaterial_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgoodsreceiptitem',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='rawmaterialgoodsreceiptitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='liabilityaccountspayable',
            name='raw_goods_receipt',
        ),
        migrations.DeleteModel(
            name='RawMaterialGoodsReceipt',
        ),
        migrations.DeleteModel(
            name='RawMaterialGoodsReceiptItem',
        ),
    ]
