# Generated by Django 4.2.4 on 2025-02-07 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_company_member_company_name'),
        ('accounting', '0048_remove_stakeholder_books_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stakeholderbook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stakeholderbook',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='equitycapital',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='equitydivident',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 21, 23, 39, 887489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='stakeholderbook',
            unique_together={('member', 'book')},
        ),
        migrations.RemoveField(
            model_name='stakeholderbook',
            name='stakeholder',
        ),
        migrations.DeleteModel(
            name='Stakeholder',
        ),
    ]
