# Generated by Django 4.2.4 on 2025-08-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_remove_rawmaterialgoodsreceiptitem_raw_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='sku',
        ),
    ]
