# Generated by Django 4.2.4 on 2025-02-07 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_alter_stakeholderbook_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 22, 24, 1, 797048, tzinfo=datetime.timezone.utc)),
        ),
    ]
