# Generated by Django 4.2.4 on 2025-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_remove_assetinventoryrawmaterial_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
