# Generated by Django 4.2.4 on 2025-08-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0030_alter_rawmaterialgood_modified_at'),
        ('accounting', '0050_assetinventoryrawmaterial_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='sku',
        ),
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='raw_material_good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operating.rawmaterialgood'),
            preserve_default=False,
        ),
    ]
