# Generated by Django 4.2.4 on 2025-02-10 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 9, 7, 50, 155366, tzinfo=datetime.timezone.utc)),
        ),
    ]
