# Generated by Django 4.2.4 on 2025-08-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_remove_assetinventoryrawmaterial_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventoryrawmaterial',
            name='unit_cost',
        ),
    ]
