# Generated by Django 4.2.4 on 2025-08-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0030_alter_rawmaterialgood_modified_at'),
        ('accounting', '0052_remove_assetinventoryrawmaterial_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilityaccountspayable',
            name='raw_material_good_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.rawmaterialgoodreceipt'),
        ),
    ]
