# Generated by Django 4.2.4 on 2025-02-10 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_alter_invoice_due_date_assetcash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 9, 53, 42, 890639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
