# Generated by Django 4.2.4 on 2025-02-10 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_remove_invoice_invoice_number_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='equitycapital',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 10, 13, 52, 456582, tzinfo=datetime.timezone.utc)),
        ),
    ]
