# Generated by Django 4.2.4 on 2025-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_liabilityaccountspayable_raw_material_good_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilityaccountspayable',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liabilityaccountspayable',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
