# Generated by Django 4.2.4 on 2025-08-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0054_liabilityaccountspayable_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilityaccountspayable',
            name='paid_with_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
    ]
