# Generated by Django 4.2.4 on 2025-02-10 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0055_equitycapital_shares_issued_alter_equitycapital_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 11, 29, 4, 797807, tzinfo=datetime.timezone.utc)),
        ),
    ]
