# Generated by Django 4.2.4 on 2025-08-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_name'),
        ('accounting', '0055_liabilityaccountspayable_paid_with_cash_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityaccountspayable',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier'),
            preserve_default=False,
        ),
    ]
