# Generated by Django 4.2.4 on 2025-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_alter_liabilityaccountspayable_supplier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashaccount',
            name='unique_book_cashaccount',
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('book', 'name', 'currency'), name='unique_book_cashaccount_currency'),
        ),
    ]
