# Generated by Django 4.2.4 on 2025-02-10 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equitycapital',
            old_name='shares_issued',
            new_name='new_shares_issued',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 11, 34, 44, 747722, tzinfo=datetime.timezone.utc)),
        ),
    ]
