# Generated by Django 4.2.4 on 2025-02-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_rename_shares_issued_equitycapital_new_shares_issued_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
