# Generated by Django 4.2.4 on 2025-08-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_remove_cashaccount_unique_book_cashaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilityaccountspayable',
            name='balance',
        ),
    ]
