# Generated by Django 4.2.4 on 2025-08-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_remove_liabilityaccountspayable_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountsreceivable',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
