# Generated by Django 4.2.4 on 2025-02-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderbook',
            name='share',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
