# Generated by Django 4.2.4 on 2025-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_stakeholderbook_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_shares',
            field=models.PositiveSmallIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='stakeholderbook',
            name='share',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
