# Generated by Django 4.2.4 on 2025-08-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_assetaccountsreceivable_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountsreceivable',
            name='paid_to_cash_accounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
            preserve_default=False,
        ),
    ]
