# Generated by Django 4.2.4 on 2025-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_book_total_shares_alter_stakeholderbook_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_shares',
            field=models.PositiveIntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='equitycapital',
            name='new_shares_issued',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stakeholderbook',
            name='share',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
