# Generated by Django 4.2.4 on 2025-08-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_assetaccountsreceivable_paid_to_cash_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='paid_to_cash_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
    ]
