# Generated by Django 4.2.4 on 2025-02-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_alter_book_total_shares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholderbook',
            old_name='share',
            new_name='shares',
        ),
    ]
