# Generated by Django 4.2.4 on 2025-08-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_alter_assetaccountsreceivable_paid_to_cash_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetaccountsreceivable',
            old_name='paid_to_cash_accounts',
            new_name='paid_to_cash_account',
        ),
    ]
