# Generated by Django 4.2.4 on 2025-08-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_rename_paid_to_cash_accounts_assetaccountsreceivable_paid_to_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcash',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assetcash',
            name='balance_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
