# Generated by Django 4.2.4 on 2025-02-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_rename_share_stakeholderbook_shares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcash',
            options={'verbose_name_plural': 'Asset Cash'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
