# Generated by Django 4.2.25 on 2026-03-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0063_assetcash_amount_assetcash_balance_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Fixed Assets',
            },
        ),
    ]
