# Generated by Django 4.2.4 on 2025-02-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0064_rename_stakeholder_equitycapital_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetcash',
            old_name='balance',
            new_name='currency_balance',
        ),
    ]
