# Generated by Django 4.2.25 on 2026-03-31 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
        ('accounting', '0064_assetfixedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityaccountspayable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier'),
        ),
    ]
