# Generated by Django 4.2.4 on 2025-02-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_rename_balance_assetcash_currency_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
