# Generated by Django 4.2.4 on 2025-02-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0066_delete_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
    ]
