# Generated by Django 4.2.25 on 2026-08-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_move_cari_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
