# Generated by Django 4.2.4 on 2025-02-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_cashaccount_book'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashaccount',
            name='unique_book_cashaccount',
        ),
    ]
