# Generated by Django 4.2.25 on 2026-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_alter_cashaccount_book_alter_cashaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitycapital',
            name='new_shares_issued',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
