# Generated by Django 4.2.25 on 2026-08-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
        ('accounting', '0069_alter_equitycapital_new_shares_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('opening', 'Opening holding'), ('capital', 'Capital contribution'), ('transfer', 'Transfer between holders'), ('buyback', 'Buyback / cancellation'), ('correction', 'Correction')], default='capital', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='accounting.equitycapital')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_share_issuances', to='authentication.member')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='accounting.stakeholderbook')),
            ],
            options={
                'verbose_name_plural': 'Share Issuances',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['stakeholder', '-date'], name='accounting__stakeho_769ac4_idx')],
            },
        ),
    ]
