# Generated by Django 4.2.4 on 2025-02-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0069_cashaccount_unique_book_cashaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityrevenue',
            name='revenue_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('other', 'Other')], default='sales'),
        ),
    ]
