# Generated by Django 4.2.4 on 2025-02-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0070_equityrevenue_revenue_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeCategory',
        ),
    ]
