# Generated by Django 4.2.4 on 2025-02-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0071_delete_income_delete_incomecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityexpense',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
            preserve_default=False,
        ),
    ]
