# Generated by Django 4.2.25 on 2026-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0071_seed_share_issuances'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Name printed on invoices, packing lists and order emails. Blank → the brand default.', max_length=200),
        ),
    ]
