# Generated by Django 4.2.4 on 2025-02-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0072_alter_equityexpense_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equitydivident',
            old_name='stakeholder',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='equityexpense',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
