# Generated by Django 4.2.4 on 2025-02-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0074_alter_equitydivident_options_delete_asset_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
