# Generated by Django 4.2.25 on 2026-08-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0071_order_billed_line_quantities_and_more'),
        ('accounting', '0075_rename_cari_ledger_to_default_cari_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='intake_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='intake_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='operating.warehouse'),
        ),
    ]
