# Generated by Django 4.2.4 on 2025-02-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0075_delete_accountbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liability',
        ),
    ]
