# Generated by Django 4.2.25 on 2026-08-26 17:29

from django.db import migrations, models


# Where each source model keeps the date the money moved. Anything absent
# here (the legacy AR/AP mirrors) has no date of its own.
SOURCE_DATE_FIELDS = {
    "equitycapital": "date_invested",
    "equityrevenue": "date",
    "equityexpense": "date",
    "equitydivident": "date",
    "intransfer": "date",
    "currencyexchange": "date",
    "payment": "date",
}


def backfill_dates(apps, schema_editor):
    """Fill the new column from each row's source.

    The GenericForeignKey is not available on historical models, so the
    content type is resolved by hand.

    Kept to a handful of queries on purpose. The obvious shape — read each
    source table whole, then UPDATE one row at a time — is fine against a
    local database and painfully slow against a remote one, which is where
    this actually runs. So each source is asked only for the primary keys
    this table refers to, and the entries are then grouped by the date they
    resolved to, one UPDATE per distinct date.
    """
    CashTransactionEntry = apps.get_model("accounting", "CashTransactionEntry")
    ContentType = apps.get_model("contenttypes", "ContentType")

    rows = list(
        CashTransactionEntry.objects.filter(date__isnull=True).values_list(
            "pk", "content_type_id", "content_pk", "created_at"
        )
    )
    if not rows:
        return

    models_by_ct = {
        ct.pk: ct.model
        for ct in ContentType.objects.filter(
            pk__in={ct_id for _, ct_id, _, _ in rows}
        )
    }

    # content_type -> {source pk: date}, asking each table only for the keys
    # this table actually points at.
    dates_by_ct = {}
    for ct_id, model_name in models_by_ct.items():
        field = SOURCE_DATE_FIELDS.get(model_name)
        if not field:
            continue  # undated source (the legacy AR/AP mirrors)
        try:
            Source = apps.get_model("accounting", model_name)
        except LookupError:
            continue
        wanted = {cpk for _, c, cpk, _ in rows if c == ct_id}
        dates_by_ct[ct_id] = dict(
            Source.objects.filter(pk__in=wanted).values_list("pk", field)
        )

    by_date = {}
    for pk, ct_id, content_pk, created_at in rows:
        value = dates_by_ct.get(ct_id, {}).get(content_pk)
        if not value:
            # Undated source, or the source row is gone. When it was
            # recorded is the best available answer.
            value = created_at.date()
        by_date.setdefault(value, []).append(pk)

    for value, pks in by_date.items():
        CashTransactionEntry.objects.filter(pk__in=pks).update(date=value)


def noop(apps, schema_editor):
    """Reversing only drops the column, which AddField already undoes."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0076_invoice_intake_plan_invoice_intake_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransactionentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_dates, noop),
    ]
