# Generated by Django 4.2.4 on 2025-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_assetaccountsreceivable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetaccountsreceivable',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='assetaccountsreceivable',
            name='due_date',
        ),
        migrations.AddField(
            model_name='assetaccountsreceivable',
            name='invoice',
            field=models.CharField(default=' 123213'),
            preserve_default=False,
        ),
    ]
