# Generated by Django 4.2.25 on 2026-08-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_cash_transaction_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransactionentry',
            name='cash_account_balance',
        ),
        migrations.RemoveField(
            model_name='cashtransactionentry',
            name='total_base_currency_balance',
        ),
    ]
