# Generated by Django 4.2.4 on 2025-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0078_remove_assetaccountsreceivable_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='invoice',
            field=models.CharField(blank=True, null=True),
        ),
    ]
