# Generated by Django 4.2.4 on 2025-02-13 11:21

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_company_city_remove_company_state_and_more'),
        ('accounting', '0079_alter_assetaccountsreceivable_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_cate', models.DateTimeField(default=accounting.models.default_due_date)),
                ('invoice_type', models.CharField(choices=[('proforma', 'Proforma'), ('commercial', 'Commercial')], default='proforma')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
            ],
        ),
        migrations.AlterField(
            model_name='assetaccountsreceivable',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice'),
        ),
    ]
