# Generated by Django 4.2.25 on 2026-08-26 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0079_book_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransactionentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
