# Generated by Django 4.2.4 on 2025-02-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0080_invoice_alter_assetaccountsreceivable_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default={}, verbose_name='ItemsInfo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
