# Generated by Django 4.2.25 on 2026-08-26 19:06

from decimal import Decimal

from django.db import migrations, models


def clear_the_untouched_default(apps, schema_editor):
    """Blank the 1.000000 that was a default, not an entry.

    Every payment carries it, because that was the field's default and
    nothing ever set it. Left in place it would now read as somebody
    asserting that one lira is one dollar. Only rows already in the book's
    base currency keep a rate of 1, and for those it is true.
    """
    Payment = apps.get_model("accounting", "Payment")
    Payment.objects.filter(exchange_rate=Decimal("1.000000")).update(
        exchange_rate=None
    )


def noop(apps, schema_editor):
    """Nothing to restore: the value being cleared carried no information."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0080_rates_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Rate to the book's base currency. Blank → the published rate for the date.", max_digits=14, null=True),
        ),
        migrations.RunPython(clear_the_untouched_default, noop),
    ]
