# Generated by Django 4.2.4 on 2025-02-13 11:37

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0081_invoice_items_invoice_paid_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default=accounting.models.invoice_items_default, verbose_name='ItemsInfo'),
        ),
    ]
