# Generated by Django 4.2.4 on 2025-02-13 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0082_alter_invoice_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetaccountsreceivable',
            options={'verbose_name_plural': 'Asset Accounts Receivables'},
        ),
        migrations.CreateModel(
            name='AssetAccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receipt', models.CharField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Accounts Payables',
            },
        ),
    ]
