# Generated by Django 4.2.25 on 2026-08-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0082_backfill_cash_entry_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitycapital',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Rate to the book's base currency. Blank → the published rate for the date.", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='equitydivident',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Rate to the book's base currency. Blank → the published rate for the date.", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='equityexpense',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Rate to the book's base currency. Blank → the published rate for the date.", max_digits=20, null=True),
        ),
    ]
