# Generated by Django 4.2.4 on 2025-02-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0083_alter_assetaccountsreceivable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventoryRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField()),
                ('stock_id', models.CharField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_of_measurement', models.CharField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('warehouse', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Inventory Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='AssetInventoryGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_of_measurement', models.CharField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('wip', 'Work in Progress'), ('finished', 'Finished Good')])),
                ('warehouse', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Inventory Goods',
            },
        ),
    ]
