# Generated by Django 4.2.25 on 2026-08-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_seed_purchase_confirm_permission'),
        ('accounting', '0083_equity_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CariTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_transfers', to='accounting.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cari_transfers', to='authentication.member')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cari_transfers', to='accounting.currencycategory')),
                ('from_cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.cariaccount')),
                ('from_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='accounting.carimovement')),
                ('to_cari', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.cariaccount')),
                ('to_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='accounting.carimovement')),
            ],
            options={
                'verbose_name': 'Account Transfer',
                'verbose_name_plural': 'Account Transfers',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['book', '-date'], name='accounting__book_id_ec39a8_idx')],
            },
        ),
    ]
