# Generated by Django 4.2.25 on 2026-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0084_caritransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='caritransfer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Rate to the book's base currency. Blank → the published rate for the date.", max_digits=14, null=True),
        ),
    ]
