# Generated by Django 4.2.4 on 2025-02-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_supplier'),
        ('accounting', '0084_assetinventoryrawmaterial_assetinventorygood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinventoryrawmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier'),
        ),
    ]
