# Generated by Django 4.2.4 on 2025-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0085_alter_assetinventoryrawmaterial_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventoryrawmaterial',
            name='raw_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default=('indirect', 'Indirect')),
        ),
    ]
