# Generated by Django 4.2.4 on 2025-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0086_assetinventoryrawmaterial_raw_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventorygood',
            name='name',
            field=models.CharField(default='helo', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='assetinventoryrawmaterial',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='unique_name_supplier'),
        ),
    ]
