# Generated by Django 4.2.25 on 2026-08-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0088_drop_order_invoice_markers'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityexpense',
            name='paid_by_cari',
            field=models.ForeignKey(blank=True, help_text='Somebody settled this for the book. Leave the cash account blank; the book ends up owing them instead.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funded_expenses', to='accounting.cariaccount', verbose_name='Paid by (current account)'),
        ),
        migrations.AlterField(
            model_name='equityexpense',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.cashaccount'),
        ),
        migrations.AddConstraint(
            model_name='equityexpense',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cash_account__isnull', False), ('paid_by_cari__isnull', True)), models.Q(('cash_account__isnull', True), ('paid_by_cari__isnull', False)), _connector='OR'), name='equityexpense_one_funding_source'),
        ),
    ]
