# Generated by Django 4.2.25 on 2026-08-28 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0090_remove_liabilityaccountspayable_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimovement',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1.00000000'), help_text='Rate from movement currency to base (USD)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='caritransfer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Rate to the book's base currency. Blank → the published rate for the date.", max_digits=16, null=True),
        ),
    ]
