# Generated by Django 4.2.25 on 2026-08-30 22:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0092_transfer_reference_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Unit price excluding VAT', max_digits=18),
        ),
    ]
