# Generated by Django 4.2.4 on 2025-02-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_supplier_company_name_and_more'),
        ('accounting', '0092_alter_assetinventorygood_unit_of_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccountspayable',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier'),
        ),
    ]
