# Generated by Django 4.2.4 on 2025-02-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_product_photo_files_product_barcode_and_more'),
        ('accounting', '0093_alter_assetaccountspayable_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventorygood',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='assetinventorygood',
            name='modified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventorygood',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='marketing.product'),
        ),
    ]
