# Generated by Django 4.2.4 on 2025-02-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0094_remove_assetinventorygood_unit_of_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventorygood',
            name='stock_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
