# Generated by Django 4.2.4 on 2025-02-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_supplier_company_name_and_more'),
        ('accounting', '0095_assetinventorygood_stock_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetAccountsPayable',
            new_name='LiabilityAccountsPayable',
        ),
        migrations.AlterModelOptions(
            name='liabilityaccountspayable',
            options={'verbose_name_plural': 'Liability Accounts Payables'},
        ),
    ]
