# Generated by Django 4.2.4 on 2025-02-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0096_rename_assetaccountspayable_liabilityaccountspayable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholderbook',
            options={'verbose_name_plural': 'Stakeholder Books'},
        ),
    ]
