# Generated by Django 4.2.4 on 2025-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0097_alter_stakeholderbook_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinventorygood',
            name='product',
        ),
    ]
