# Generated by Django 4.2.4 on 2025-02-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0098_remove_assetinventorygood_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange_destination', to='accounting.cashaccount')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange_source', to='accounting.cashaccount')),
            ],
        ),
    ]
