# Generated by Django 4.2.25 on 2026-09-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_company_created_by_contact_created_by'),
        ('authentication', '0019_alter_permission_description_alter_permission_name'),
        ('accounting', '0098_rename_cari_to_current_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currentaccount',
            name='uniq_cari_book_contact',
        ),
        migrations.RemoveConstraint(
            model_name='currentaccount',
            name='uniq_cari_book_company',
        ),
        migrations.RemoveConstraint(
            model_name='currentaccount',
            name='uniq_cari_book_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='equityexpense',
            name='equityexpense_one_funding_source',
        ),
        migrations.RemoveIndex(
            model_name='checkorpromissorynote',
            name='accounting__cari_id_908b24_idx',
        ),
        migrations.RemoveIndex(
            model_name='currentaccountmovement',
            name='accounting__cari_id_b59f56_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__cari_id_fbc5cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='accounting__cari_id_5d7004_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='accounting__cari_id_217644_idx',
        ),
        migrations.RenameIndex(
            model_name='currentaccount',
            new_name='accounting__book_id_cb223c_idx',
            old_name='accounting__book_id_907f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='currentaccount',
            new_name='accounting__book_id_2d1d5d_idx',
            old_name='accounting__book_id_ad5e7d_idx',
        ),
        migrations.RenameIndex(
            model_name='currentaccountmovement',
            new_name='accounting__book_id_a1c98d_idx',
            old_name='accounting__book_id_2960b3_idx',
        ),
        migrations.RenameIndex(
            model_name='currentaccountmovement',
            new_name='accounting__movemen_d9cdb0_idx',
            old_name='accounting__movemen_34bdc4_idx',
        ),
        migrations.RenameIndex(
            model_name='currentaccounttransfer',
            new_name='accounting__book_id_e097db_idx',
            old_name='accounting__book_id_ec39a8_idx',
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_account_accounts', to='accounting.book'),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_account_accounts', to='crm.company'),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_account_accounts', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_current_account_accounts', to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='default_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_account_accounts', to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_account_accounts', to='crm.supplier'),
        ),
        migrations.AlterField(
            model_name='currentaccountmovement',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_account_movements', to='accounting.book'),
        ),
        migrations.AlterField(
            model_name='currentaccountmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_current_account_movements', to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='currentaccountsettings',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_account_settings', to='accounting.book'),
        ),
        migrations.AlterField(
            model_name='currentaccountsettings',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_account_settings_default', to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='currentaccounttransfer',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_account_transfers', to='accounting.book'),
        ),
        migrations.AlterField(
            model_name='currentaccounttransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_current_account_transfers', to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='currentaccounttransfer',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_account_transfers', to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_account_payments', to='accounting.cashaccount'),
        ),
        migrations.AddIndex(
            model_name='checkorpromissorynote',
            index=models.Index(fields=['current_account', '-due_date'], name='accounting__current_9adfde_idx'),
        ),
        migrations.AddIndex(
            model_name='currentaccountmovement',
            index=models.Index(fields=['current_account', '-date'], name='accounting__current_bdf9de_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['current_account', '-date'], name='accounting__current_5d875f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['current_account'], name='accounting__current_8a708f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['current_account', '-date'], name='accounting__current_5917b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='currentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('book', 'contact'), name='uniq_current_account_book_contact'),
        ),
        migrations.AddConstraint(
            model_name='currentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('book', 'company'), name='uniq_current_account_book_company'),
        ),
        migrations.AddConstraint(
            model_name='currentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('book', 'supplier'), name='uniq_current_account_book_supplier'),
        ),
        migrations.AddConstraint(
            model_name='equityexpense',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cash_account__isnull', False), ('paid_by_current_account__isnull', True)), models.Q(('cash_account__isnull', True), ('paid_by_current_account__isnull', False)), _connector='OR'), name='equityexpense_one_funding_source'),
        ),
    ]
