# Generated by Django 4.2.4 on 2025-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0099_currencyexchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyexchange',
            old_name='source',
            new_name='from_cash_account',
        ),
        migrations.RenameField(
            model_name='currencyexchange',
            old_name='destination',
            new_name='to_cash_account',
        ),
    ]
