# Generated by Django 4.2.25 on 2026-09-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0099_current_account_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartaccount',
            name='is_control',
            field=models.BooleanField(default=False, help_text='Summarises a subsidiary ledger (current accounts, cash accounts).'),
        ),
    ]
