# Generated by Django 4.2.4 on 2025-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0100_rename_source_currencyexchange_from_cash_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyexchange',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intransfer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
