# Generated by Django 4.2.25 on 2026-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0100_chartaccount_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='code',
            field=models.CharField(help_text='e.g., ACC-001', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentaccountsettings',
            name='current_account_code_prefix',
            field=models.CharField(default='ACC', max_length=10),
        ),
    ]
