# Generated by Django 4.2.25 on 2026-09-09 18:16

from django.db import migrations, models

def stamp_the_current_year(apps, schema_editor):
    """Say that the counters already running belong to THIS year's run.

    Without this they read as null, the next document taken would see a
    year it has not issued under, restart the sequence at 1 — and Laleli's
    invoice counter is at 109. The first invoice after the deploy would be
    INV-2026-000001, a number already on a customer's paperwork, and the
    (book, series, number) constraint would refuse the save.

    Only rows that have issued something are stamped. A counter still at 1
    has nothing to protect and is left null, so it starts cleanly whenever
    its first document is taken.
    """
    from django.utils import timezone
    year = timezone.now().year
    Settings = apps.get_model("accounting", "CurrentAccountSettings")
    Settings.objects.filter(next_invoice_seq__gt=1).update(invoice_seq_year=year)
    Settings.objects.filter(next_payment_seq__gt=1).update(payment_seq_year=year)


def unstamp(apps, schema_editor):
    """Reversing this drops the year, which is what the column did before."""
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0101_alter_currentaccount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccountsettings',
            name='invoice_seq_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentaccountsettings',
            name='payment_seq_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(stamp_the_current_year, unstamp),
    ]
