# Generated by Django 4.2.4 on 2025-02-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0101_currencyexchange_date_intransfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='currency_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
