# Generated by Django 4.2.25 on 2026-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0102_annual_number_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccountmovement',
            name='account_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Rate from movement currency to the account's own currency, when that is not the base. Blank → the published rate for the date.", max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='account_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Rate to the account's own currency, when that is not the base. Blank → the published rate for the date.", max_digits=14, null=True),
        ),
    ]
