# Generated by Django 4.2.25 on 2026-09-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0103_account_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccount',
            name='mirror_account',
            field=models.OneToOneField(blank=True, help_text="The other book's account for the same inter-company debt. Movements posted here are mirrored there with the opposite sign.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.currentaccount'),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='mirror_since',
            field=models.DateTimeField(blank=True, help_text='Movements created from this moment on are mirrored.', null=True),
        ),
        migrations.AddField(
            model_name='currentaccountmovement',
            name='mirror_of',
            field=models.OneToOneField(blank=True, editable=False, help_text='The movement on the paired inter-company account this row mirrors.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirror', to='accounting.currentaccountmovement'),
        ),
        migrations.AlterField(
            model_name='currentaccountmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('order_sale', 'Sales Order'), ('invoice_sale', 'Sales Invoice'), ('invoice_purchase', 'Purchase Invoice'), ('return_sale', 'Sales Return'), ('return_purchase', 'Purchase Return'), ('collection', 'Collection'), ('payment', 'Payment'), ('advance_in', 'Advance Received'), ('advance_out', 'Advance Given'), ('interest', 'Interest / Late Fee'), ('discount', 'Discount'), ('adjustment', 'Offset / Adjustment'), ('check_in', 'Check/Note Received'), ('check_out', 'Check/Note Given'), ('legacy_ar', 'Legacy - Receivable'), ('legacy_ap', 'Legacy - Payable'), ('intercompany', 'Inter-company mirror')], max_length=20),
        ),
    ]
