# Generated by Django 4.2.25 on 2026-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0104_intercompany_mirror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccount',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Customer & Supplier'), ('staff', 'Staff'), ('intercompany', 'Inter-company'), ('other', 'Other')], default='customer', max_length=20),
        ),
    ]
