# Generated by Django 4.2.25 on 2026-09-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0091_warehouse_costs_not_negative'),
        ('accounting', '0106_movement_type_write_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='for_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_purchases', to='operating.order'),
        ),
    ]
