# Generated by Django 4.2.25 on 2026-09-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0107_invoice_for_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaccountsettings',
            name='invoice_language',
        ),
    ]
