# Generated by Django 4.2.25 on 2026-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0108_drop_invoice_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentaccountmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('order_sale', 'Sales Order'), ('invoice_sale', 'Sales Invoice'), ('invoice_purchase', 'Purchase Invoice'), ('return_sale', 'Sales Return'), ('return_purchase', 'Purchase Return'), ('collection', 'Collection'), ('payment', 'Payment'), ('advance_in', 'Advance Received'), ('advance_out', 'Advance Given'), ('interest', 'Interest / Late Fee'), ('discount', 'Discount'), ('write_off', 'Bad Debt Written Off'), ('adjustment', 'Offset / Adjustment'), ('fx_adjustment', 'Exchange Rate Difference'), ('check_in', 'Check/Note Received'), ('check_out', 'Check/Note Given'), ('legacy_ar', 'Legacy - Receivable'), ('legacy_ap', 'Legacy - Payable'), ('intercompany', 'Inter-company mirror')], max_length=20),
        ),
    ]
