# Generated by Django 4.2.25 on 2026-09-24 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0110_payment_published_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Purchase created'), ('status', 'Status changed'), ('item_added', 'Item added'), ('item_removed', 'Item removed'), ('item_updated', 'Item updated'), ('field', 'Field updated')], db_index=True, max_length=16)),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('item_label', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('purchase', 'on the purchase'), ('order', 'from the customer order')], default='purchase', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_changes', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='accounting.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['invoice', '-created_at'], name='accounting__invoice_2e5152_idx')],
            },
        ),
    ]
