# Generated by Django 4.2.25 on 2026-10-06 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0113_movement_type_balance_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='debit',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18),
        ),
    ]
