# Generated by Django 4.2.25 on 2026-01-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_chat_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
