# Generated by Django 4.2.25 on 2026-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teamtask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('red', 'Red'), ('gray', 'Gray'), ('pink', 'Pink'), ('teal', 'Teal')], default='blue', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='team.team')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('team', 'title')},
            },
        ),
        migrations.AddField(
            model_name='teamtask',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='team.teamboardcolumn'),
        ),
    ]
