# Generated by Django 5.2.7 on 2026-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_teamtaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='google_space_id',
            field=models.CharField(blank=True, help_text='Google Chat Space ID if connected', max_length=255, null=True),
        ),
    ]
