# Generated by Django 4.2.25 on 2026-02-04 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0010_teamtaskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='team_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_team_tasks_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
