# Generated by Django 4.2.25 on 2026-02-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_teamtask_assignees_alter_teamtask_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='team.team'),
        ),
    ]
