# Generated by Django 4.2.25 on 2026-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_teammeeting_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
