# Generated by Django 5.2.7 on 2026-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_seed_belino_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='image_url',
            field=models.URLField(blank=True, help_text='Hero/seasons kapak görseli'),
        ),
        migrations.AlterField(
            model_name='homesectioncard',
            name='item_count',
            field=models.IntegerField(default=0, help_text="Görsel rozet (örn. '248 ürün')"),
        ),
        migrations.AlterField(
            model_name='homesectioncard',
            name='key',
            field=models.SlugField(blank=True, help_text='örn. ss26', max_length=60),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='feature_image_url',
            field=models.URLField(blank=True, help_text='/home/... veya tam URL'),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='href',
            field=models.CharField(blank=True, help_text="Boş bırakılırsa kategori veya children'a göre çözülür", max_length=300),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='swatch',
            field=models.CharField(blank=True, help_text="Hex renk — alt menü swatch'i için (örn. #0E0E0C)", max_length=20),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='domain',
            field=models.CharField(blank=True, help_text='örn. belino.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='key',
            field=models.SlugField(help_text="URL/API key — örn. 'belino'", max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='name',
            field=models.CharField(help_text="Görünür ad — örn. 'Belino B2B'", max_length=120),
        ),
        migrations.AlterField(
            model_name='trustbadge',
            name='icon_key',
            field=models.CharField(blank=True, help_text='shield, percent, truck, card, bolt vs (Belino tarafında SVG mapping)', max_length=40),
        ),
    ]
