# Generated by Django 4.2.4 on 2023-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(to='crm.client'),
        ),
    ]
