# Generated by Django 4.2.4 on 2023-09-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_text_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company'),
        ),
        migrations.AlterField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.contact'),
        ),
    ]
