# Generated by Django 4.2.4 on 2025-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_contact_backgroundinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='backgroundInfo',
            field=models.TextField(blank=True, max_length=200, verbose_name='Background info'),
        ),
    ]
