# Generated by Django 4.2.4 on 2023-09-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_note_company_alter_note_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
