# Generated by Django 4.2.4 on 2023-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
