# Generated by Django 4.2.4 on 2024-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_note_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='backgroundInfo',
            field=models.CharField(blank=True, max_length=400, verbose_name='Background info'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Company Name (required)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip'),
        ),
    ]
