# Generated by Django 4.2.4 on 2024-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_company_created_at_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
