# Generated by Django 4.2.4 on 2024-05-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip_code',
        ),
    ]
