# Generated by Django 4.2.4 on 2025-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_clientgroup_company_group_contact_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('qualified', 'Qualified')], default='prospect'),
        ),
    ]
