# Generated by Django 4.2.4 on 2025-10-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent_count', models.IntegerField(default=0)),
                ('stopped_reason', models.CharField(blank=True, help_text="Reason why follow-ups were stopped (e.g., 'status_changed', 'max_emails_reached', 'reply_received')", max_length=100, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='crm.company')),
            ],
            options={
                'verbose_name_plural': 'Company Follow Ups',
            },
        ),
    ]
