# Generated by Django 4.2.4 on 2025-02-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
