# Generated by Django 5.2.7 on 2026-05-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_convert_contact_email_phone_to_arrays'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='linked_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_suppliers', to='crm.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='linked_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_suppliers', to='crm.contact'),
        ),
    ]
