# Generated by Django 4.2.25 on 2026-10-01 08:08

from django.db import migrations, models


def set_doubles_apart(apps, schema_editor):
    """Give every name held twice a numbered suffix on all but the oldest
    record — "Ada", "Ada (2)" — so the constraints in 0024 can go on.

    Nothing is merged or deleted here: which of two records is the real
    one is a judgement for whoever knows the customer, and a migration
    that cannot be applied takes the deploy down with it. A renamed
    double is at least visible, and can be merged by hand afterwards.
    """
    def run(model, field, queryset=None):
        rows = queryset if queryset is not None else model.objects.all()
        held = {(getattr(r, field) or "").strip().lower()
                for r in model.objects.all()}
        seen = set()
        limit = model._meta.get_field(field).max_length
        for row in rows.order_by("pk"):
            name = (getattr(row, field) or "").strip()
            key = name.lower()
            if not key:
                continue
            if key not in seen:
                seen.add(key)
                continue
            n = 2
            while True:
                suffix = f" ({n})"
                candidate = name[:limit - len(suffix)] + suffix
                if candidate.lower() not in held:
                    break
                n += 1
            held.add(candidate.lower())
            seen.add(candidate.lower())
            model.objects.filter(pk=row.pk).update(**{field: candidate})

    Supplier = apps.get_model("crm", "Supplier")
    run(apps.get_model("crm", "Company"), "name")
    run(apps.get_model("crm", "Contact"), "name")
    run(Supplier, "company_name")
    run(Supplier, "contact_name",
        Supplier.objects.filter(models.Q(company_name__isnull=True) | models.Q(company_name="")))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_backfill_supplier_created_by'),
    ]

    operations = [
        migrations.RunPython(set_doubles_apart, migrations.RunPython.noop),
    ]
