# Generated by Django 4.2.25 on 2026-10-01 08:08

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    # Apart from 0023 on purpose: Postgres will not build an index on a
    # table the same transaction has just rewritten rows of.
    dependencies = [
        ('crm', '0023_set_duplicate_names_apart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_company_name_ci', violation_error_message='A company with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_contact_name_ci', violation_error_message='A contact with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('company_name'), condition=models.Q(('company_name__gt', '')), name='uniq_supplier_company_name_ci', violation_error_message='A supplier with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('contact_name'), condition=models.Q(models.Q(('company_name__isnull', True), ('company_name', ''), _connector='OR'), ('contact_name__gt', '')), name='uniq_supplier_contact_name_ci', violation_error_message='A supplier with this name already exists.'),
        ),
    ]
