"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# below is for loading environment variables for establishing security
# from dotenv import load_dotenv
from decouple import config as _default_config, Config, RepositoryEnv


# load_dotenv()
# print(os.getenv('DATABASE'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------
# Multi-tenant env profile loader
# ----------------------------------------------------------------------
# Default behaviour (no ENV_PROFILE set): read .env, identical to the
# original demfirat setup — public schema, demfirat data — nothing
# changes for that deployment.
#
# When ENV_PROFILE=foo is set, we load .env.foo instead. Lets one ERP
# codebase serve multiple brands (Belino, future tenants) where each
# brand has its own DB credentials and target schema.
#   ENV_PROFILE=belino python manage.py runserver 8001
# ----------------------------------------------------------------------
_env_profile = os.environ.get("ENV_PROFILE", "").strip()
if _env_profile:
    _env_path = BASE_DIR / f".env.{_env_profile}"
    if _env_path.exists():
        config = Config(RepositoryEnv(str(_env_path)))
        print(f"[ENV_PROFILE] Using {_env_path.name}")
    else:
        config = _default_config
        print(f"[ENV_PROFILE] {_env_path.name} not found, falling back to .env")
else:
    config = _default_config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# Google OAuth Settings
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default="") # Fixed case sensitivity

# Confirmation password gate for restoring (un-cancelling) a cancelled invoice.
INVOICE_RESTORE_PASSWORD = config("INVOICE_RESTORE_PASSWORD", default="demfiratkarven")

ALLOWED_HOSTS = [
    ".vercel.app",
    "erp.demfirat.com",
    "demfirat.com",
    "127.0.0.1",
    "localhost",
    "app.nejum.com",
    "www.nejum.com",
    "demfirat.nejum.com",
    "erp-production-52e2.up.railway.app",
    "erp-2hs3.onrender.com",
    '192.168.1.106',
    '48c4e0a19cf1.ngrok-free.app',
]

# CSRF_TRUSTED_ORIGINS = ['https://*.demfirat.com','https://*.127.0.0.1']
CSRF_TRUSTED_ORIGINS = [
    "https://*.demfirat.com",
    "https://*.nejum.com",
    "https://*.vercel.app",
    "https://*.up.railway.app",   # any Railway-hosted service URL
    "https://*.onrender.com",     # Render fallback
    "https://48c4e0a19cf1.ngrok-free.app",
    # Inline image upload from Belino dev server (cross-origin POST).
    "http://localhost:3010",
    "http://127.0.0.1:3010",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# ------------------------------------------------------------------
# Reverse-proxy aware HTTPS detection
# ------------------------------------------------------------------
# Railway / Render / Vercel / Heroku terminate TLS at the edge and
# forward plain HTTP to the app, but they also set
# X-Forwarded-Proto: https. Without this header mapping Django thinks
# the request is HTTP, sees the request's Origin header as `https://…`,
# and rejects it as a CSRF mismatch (403). Telling Django to honour
# the forwarded scheme fixes both CSRF and any redirect-to-https logic.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Cookies travel over HTTPS only in production. Keep them lax in DEBUG
# so local dev on http://localhost keeps working.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# CORS Settings for Next.js Frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3010",  # Belino B2B frontend
    "http://127.0.0.1:3010",
    "https://karvenhome.com",
    "https://www.karvenhome.com",
    "https://demfirat.com",
    "https://erp-production-52e2.up.railway.app",
    "https://www.demfirat.com",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Below is added for django OAuth
# we may need to change to something else other than 1, but that's for later
# SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "corsheaders",  # CORS support for Next.js frontend
    "erp",
    "todo",
    "crm",
    "accounting",
    "authentication",
    "operating",
    "marketing",
    "email_automation",  # Email automation system
    "notifications",  # Notification system
    "team",  # Team management system
    "notes", # My Notes system
    "procurement", # Procurement system
    "current_account",  # Cari Hesap (current account / customer-supplier ledger)
    "storefront",  # Online store CMS (header menu, home sections, featured products)
    "django_htmx",
    "crispy_forms",
    "crispy_bootstrap5",
    # below is for google auth

    # below is for google auth
    # "django.contrib.sites",
    # "allauth",  # this allows us to do other authentications beside the standard one (like google)
    # "allauth.account",
    # "allauth.socialaccount",
    # "allauth.socialaccount.providers.google",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# SOCIALACCOUNT_PROVIDERS = {
#     "google": {
#         # this is our credentials
#         "SCOPE": [
#             "profile",
#             "email",
#         ],
#         "AUTH_PARAMS": {
#             "access_type": "online",
#         },
#     }
# }


# Don't know if below does any shit.
# SOCIALACCOUNT_LOGIN_ON_GET = True
# TEMPLATE_CONTEXT_PROCESSORS = [
#     # ...
#     "allauth.socialaccount.context_processors.socialaccount",
#     # ...
# ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - must be before CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Force English as the default for users with no explicit language
    # cookie/session — must run BEFORE LocaleMiddleware so that one
    # doesn't override us based on Accept-Language.
    "erp.middleware.ForceEnglishDefaultMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # i18n: detect/activate user language
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Request-scoped current user for the order audit trail (must come
    # after AuthenticationMiddleware so request.user is resolved).
    "operating.audit.CurrentUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    # "erp.middleware.PerformanceLoggingMiddleware",  # Performance monitoring
    # "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "erp.urls"

# ------------------------------------------------------------------
# BRAND switch — in production, set ONE env var (BRAND=belino) and
# every brand-specific setting flips together. Individual env vars
# (DB_SCHEMA, BRAND_NAME, …) still take precedence when set, so a
# deployment can override any single value without losing the rest.
# ------------------------------------------------------------------
BRAND = config("BRAND", default="").strip().lower() or "demfirat"

BRAND_DEFAULTS = {
    "demfirat": {
        "DB_SCHEMA": "public",
        "BRAND_NAME": "Demfirat",
        "BRAND_LEGAL_SUFFIX": "SAN. TİC. LTD. ŞTİ.",
        "BRAND_ADDRESS": "Ergene 1. OSB Mahallesi, D100 Cad. no.38 Ergene / TEKİRDAĞ",
        "BRAND_PHONE": "+90 (501) 057-1884",
        "BRAND_FAX": "+90 (282) 675-1552",
        "BRAND_EMAIL": "info@demfirat.com",
        "BRAND_TAX_OFFICE": "",
        "BRAND_TAX_NUMBER": "",
        "BRAND_LOGO_URL": "",
        # Empty → invoices use the legacy dashed format INV-YEAR-NNNNNN
        # (see CariSettings.next_invoice_number). Set a non-empty value
        # to switch to the compact PREFIX+YEAR+SEQ shape.
        "BRAND_INVOICE_PREFIX": "",
        "UI_THEME": "nejum",
        "CLIENT_PUBLIC_URL": "http://localhost:3000",
        "STOREFRONT_PREVIEW_URL": "http://localhost:3000/",
    },
    "belino": {
        "DB_SCHEMA": "BELINO",
        "BRAND_NAME": "Belino",
        "BRAND_LEGAL_SUFFIX": "SAN. TİC. LTD. ŞTİ.",
        "BRAND_ADDRESS": "",
        "BRAND_PHONE": "",
        "BRAND_FAX": "",
        "BRAND_EMAIL": "",
        "BRAND_TAX_OFFICE": "",
        "BRAND_TAX_NUMBER": "",
        "BRAND_LOGO_URL": "",
        "BRAND_INVOICE_PREFIX": "BLN",
        "UI_THEME": "nejum",
        "CLIENT_PUBLIC_URL": "http://localhost:3010",
        "STOREFRONT_PREVIEW_URL": "http://localhost:3010/",
    },
}
_brand_cfg = BRAND_DEFAULTS.get(BRAND, BRAND_DEFAULTS["demfirat"])

# Each setting: explicit env var wins, else the brand profile default.
UI_THEME = config("UI_THEME", default=_brand_cfg["UI_THEME"]).strip()
DB_SCHEMA = config("DB_SCHEMA", default=_brand_cfg["DB_SCHEMA"]).strip()
BRAND_NAME = config("BRAND_NAME", default=_brand_cfg["BRAND_NAME"]).strip()
BRAND_LEGAL_SUFFIX = config("BRAND_LEGAL_SUFFIX", default=_brand_cfg.get("BRAND_LEGAL_SUFFIX", "")).strip()
BRAND_ADDRESS = config("BRAND_ADDRESS", default=_brand_cfg.get("BRAND_ADDRESS", "")).strip()
BRAND_PHONE = config("BRAND_PHONE", default=_brand_cfg.get("BRAND_PHONE", "")).strip()
BRAND_FAX = config("BRAND_FAX", default=_brand_cfg.get("BRAND_FAX", "")).strip()
BRAND_EMAIL = config("BRAND_EMAIL", default=_brand_cfg.get("BRAND_EMAIL", "")).strip()
BRAND_TAX_OFFICE = config("BRAND_TAX_OFFICE", default=_brand_cfg.get("BRAND_TAX_OFFICE", "")).strip()
BRAND_TAX_NUMBER = config("BRAND_TAX_NUMBER", default=_brand_cfg.get("BRAND_TAX_NUMBER", "")).strip()
BRAND_LOGO_URL = config("BRAND_LOGO_URL", default=_brand_cfg.get("BRAND_LOGO_URL", "")).strip()
BRAND_INVOICE_PREFIX = config("BRAND_INVOICE_PREFIX", default=_brand_cfg.get("BRAND_INVOICE_PREFIX", "")).strip()
CLIENT_PUBLIC_URL = config("CLIENT_PUBLIC_URL", default=_brand_cfg["CLIENT_PUBLIC_URL"]).strip()
STOREFRONT_PREVIEW_URL = config(
    "STOREFRONT_PREVIEW_URL", default=_brand_cfg["STOREFRONT_PREVIEW_URL"]
).strip()
print(f"[BRAND] Active brand: {BRAND} (schema={DB_SCHEMA}, preview={STOREFRONT_PREVIEW_URL})")

_template_dirs = [os.path.join(BASE_DIR, "templates")]
if UI_THEME:
    _theme_dir = os.path.join(BASE_DIR, "templates", "themes", UI_THEME)
    if os.path.isdir(_theme_dir):
        _template_dirs.insert(0, _theme_dir)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": _template_dirs,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # The below helps to put the view function variable global in all templates
                "erp.context_processors.last_ten_entities",
                "erp.context_processors.client_groups",
                "erp.context_processors.all_members",
                "erp.context_processors.ui_theme",
                # Removed: product_categories and suppliers - not used in base.html
                # "erp.context_processors.product_categories",
                # "erp.context_processors.suppliers",
            ],
        },
    },
]

# WSGI_APPLICATION = "erp.wsgi.application"
WSGI_APPLICATION = "erp.wsgi.app"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# DATABASE_URL = 'postgresql://postgres:z5nJKvkJjjrYwgHZZYRz@containers-us-west-99.railway.app:6547/railway'
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE"),
        # name of database
        "NAME": config("DB_NAME"),
        # user that created the database, or have access to it
        "USER": config("DB_USER"),
        # user password
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),  # an empty string means localhost
        "PORT": config("DB_PORT"),
        # Connection pooling for better performance
        "CONN_MAX_AGE": 0,  # Must be 0 when using PgBouncer/Railway poolers to prevent InterfaceError
        "CONN_HEALTH_CHECKS": True,  # Prevent InterfaceError when connection drops
        "OPTIONS": {
            # PostgreSQL specific optimizations
            "connect_timeout": 10,
            # Per-brand schema isolation. Uses the already-resolved
            # DB_SCHEMA constant (line ~258) which honours BRAND_DEFAULTS,
            # so `BRAND=belino` correctly scopes the connection to the
            # BELINO schema even when .env has no explicit DB_SCHEMA.
            # NOTE: Re-calling config("DB_SCHEMA", default="public") here
            # ignores BRAND_DEFAULTS and silently fell back to public —
            # exactly the bug that hid Belino data behind the demfirat
            # connection.
            "options": (
                f'-c search_path="{DB_SCHEMA}",public'
            ),
        },
        "TEST": {
            "NAME": "nejum_test",  # test DB
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True
USE_L10N = True
USE_TZ = True

from django.utils.translation import gettext_lazy as _i18n_lazy

LANGUAGES = [
    ("en", _i18n_lazy("English")),
    ("tr", _i18n_lazy("Türkçe")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = '/static/'

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# In DEBUG: serve directly from app dirs without manifest hashing so newly
# added static files are picked up without collectstatic / restart.
# In production: use WhiteNoise's hashed/compressed manifest storage.
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Media Files (For user uploaded files (dynamic not static))
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Bunny CDN Configuration
# Set USE_BUNNY_CDN=True in .env to enable Bunny CDN for new uploads
USE_BUNNY_CDN = config("USE_BUNNY_CDN", default=False, cast=bool)
BUNNY_STORAGE_API_KEY = config("BUNNY_STORAGE_API_KEY", default="")
BUNNY_ACCOUNT_API_KEY = config("BUNNY_ACCOUNT_API_KEY", default="")
BUNNY_STORAGE_ZONE = config("BUNNY_STORAGE_ZONE", default="")
BUNNY_STORAGE_REGION = config("BUNNY_STORAGE_REGION", default="")  # Empty for main region
BUNNY_CDN_URL = config("BUNNY_CDN_URL", default="")


# specify the URL where Django should redirect unauthenticated users:
# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

if not DEBUG:
    STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = []


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# AUTHENTICATION_BACKENDS = (
#     # Needed to login by username in Django admin, regardless of 'allauth'
#     "django.contrib.auth.backends.ModelBackend",
#     # Logging in with allauth
#     "allauth.account.auth_backends.AuthenticationBackend",
# )

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/authentication/signin"
LOGOUT_REDIRECT_URL = "/authentication/index"
# LOGOUT_REDIRECT_URL = "/"


# for accounting model
BASE_CURRENCY_CODE = "USD"

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Follow-up email settings
FOLLOWUP_EMAIL_FROM = config('FOLLOWUP_EMAIL_FROM', default=EMAIL_HOST_USER)
FOLLOWUP_SENDER_NAME = config('FOLLOWUP_SENDER_NAME', default='Nejum ERP Team')
FOLLOWUP_SENDER_TITLE = config('FOLLOWUP_SENDER_TITLE', default='Sales Team')
FOLLOWUP_SENDER_COMPANY = config('FOLLOWUP_SENDER_COMPANY', default='Nejum')

# Gmail OAuth2 Settings for Email Automation
GMAIL_CLIENT_ID = config('GMAIL_CLIENT_ID', default='')
GMAIL_CLIENT_SECRET = config('GMAIL_CLIENT_SECRET', default='')
GMAIL_REDIRECT_URI = config('GMAIL_REDIRECT_URI', default='http://localhost:8000/email/oauth2callback/')
GMAIL_SCOPES = [
    'https://www.googleapis.com/auth/gmail.send',
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/gmail.modify'
]

# Order deletion guard — admins delete freely; anyone else must supply
# this password (checked server-side in delete_order/bulk_delete_orders).
# Override via env without a code change if it ever leaks.
ORDER_DELETE_PASSWORD = config("ORDER_DELETE_PASSWORD", default="demfiratkarven")

# File Upload Settings
# Increase limits to allow multiple image uploads for products and variants
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB (default is 2.5 MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB (default is 2.5 MB)

# Django Debug Toolbar — opt-in via DEBUG_TOOLBAR=True in .env (and only
# in DEBUG mode). Its template-context inspection alone added ~3s per
# request on heavy pages (it reprs the whole context, triggering dozens
# of lazy FK queries against the remote DB), so it must never be on by
# default for daily work.
if DEBUG and config("DEBUG_TOOLBAR", default=False, cast=bool):
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = [
        "127.0.0.1",
        "localhost",
    ]
