# Generated by Django 4.2.25 on 2026-09-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_brandprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_color',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
