# Generated by Django 4.2.25 on 2026-10-04 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0003_brandprofile_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('access_token', models.TextField(blank=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=40)),
                ('shipped_template', models.CharField(blank=True, max_length=120)),
                ('template_language', models.CharField(blank=True, max_length=10)),
                ('default_country_code', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp settings',
                'verbose_name_plural': 'WhatsApp settings',
            },
        ),
    ]
