# Generated by Django 4.2.25 on 2026-10-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_whatsappsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='template_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
