# Generated by Django 4.2.4 on 2024-08-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawMaterialCategorys',
            new_name='RawMaterialCategory',
        ),
    ]
