# Generated by Django 4.2.4 on 2024-08-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0002_rename_rawmaterialcategorys_rawmaterialcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operating.rawmaterialcategory'),
            preserve_default=False,
        ),
    ]
