# Generated by Django 4.2.4 on 2024-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0003_rawmaterial_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_rpm', models.PositiveIntegerField()),
                ('domain', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
