# Generated by Django 4.2.4 on 2025-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0004_orderitem_notes_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
