# Generated by Django 4.2.4 on 2025-06-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0008_alter_orderitem_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='variant',
            new_name='product_variant',
        ),
    ]
