# Generated by Django 4.2.4 on 2025-07-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0009_rename_variant_orderitem_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='machine',
            name='workstation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='operating.workstation'),
            preserve_default=False,
        ),
    ]
