# Generated by Django 4.2.4 on 2025-07-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0010_workstation_rename_notes_orderitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='price',
        ),
    ]
