# Generated by Django 4.2.4 on 2025-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0011_rename_unit_price_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
