# Generated by Django 4.2.4 on 2024-11-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0014_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
