# Generated by Django 4.2.4 on 2025-07-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0014_orderitem_created_at_orderitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='qr_code_url',
        ),
        migrations.CreateModel(
            name='OrderItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='operating.orderitem')),
            ],
        ),
    ]
