# Generated by Django 4.2.4 on 2024-11-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0015_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('variant', models.JSONField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('raw_materials', models.ManyToManyField(blank=True, to='operating.rawmaterial')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operating.unitcategory')),
            ],
        ),
    ]
