# Generated by Django 4.2.4 on 2025-07-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0015_remove_orderitem_qr_code_url_orderitemunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='target_quantity_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('in_repair', 'In Repair'), ('ready', 'Ready for Shipment'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='operating.order')),
            ],
        ),
    ]
