# Generated by Django 4.2.4 on 2025-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0016_orderitem_target_quantity_per_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('in_repair', 'In Repair'), ('ready', 'Ready for Shipment'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
