# Generated by Django 4.2.4 on 2025-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0093_alter_assetaccountspayable_supplier'),
        ('operating', '0017_remove_rawmaterial_suppliercompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('sku', models.CharField(max_length=12, unique=True)),
                ('ingredient', models.ManyToManyField(related_name='products', to='accounting.assetinventoryrawmaterial')),
            ],
        ),
    ]
