# Generated by Django 4.2.4 on 2025-07-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0018_alter_orderitemunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
