# Generated by Django 4.2.4 on 2025-02-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0018_alter_machine_name_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
