# Generated by Django 4.2.4 on 2025-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0020_pack_packeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
