# Generated by Django 4.2.4 on 2025-08-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0031_alter_productcategory_image'),
        ('accounting', '0044_rename_amount_base_currency_cashtransactionentry_amount_in_base_currency_and_more'),
        ('operating', '0021_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.book')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods', to='marketing.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods', to='marketing.productvariant')),
            ],
        ),
    ]
