# Generated by Django 4.2.4 on 2025-08-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_rename_rawgoodsreceipt_rawmaterialgoodsreceipt_and_more'),
        ('marketing', '0031_alter_productcategory_image'),
        ('operating', '0022_finishedgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('name', models.CharField()),
                ('supplier_sku', models.CharField(blank=True, null=True)),
                ('sku', models.CharField()),
                ('unit_of_measurement', models.CharField(blank=True, choices=[('units', 'Unit'), ('mt', 'Meter'), ('kg', 'Kilogram'), ('l', 'Liter'), ('bx', 'Box')], default=('units', 'Unit'), null=True)),
                ('raw_type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default=('direct', 'Direct'))),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset_inventory_raw_material_good', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='accounting.assetinventoryrawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialGoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_material_good_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.rawmaterialgoodsreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='WorkInProgressGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_goods', to='operating.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_goods', to='marketing.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wip_goods', to='marketing.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='FinishedGood',
        ),
    ]
