# Generated by Django 4.2.4 on 2025-08-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_company_name'),
        ('accounting', '0047_assetinventoryrawmaterial_name_and_more'),
        ('operating', '0023_rawmaterialgood_rawmaterialgooditem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgooditem',
            name='raw_material_good_receipt',
        ),
        migrations.AddField(
            model_name='rawmaterialgood',
            name='raw_material',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operating_data', to='accounting.assetinventoryrawmaterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='raw_material_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operating.rawmaterialgood'),
        ),
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='raw_material_goods_receipt_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.rawmaterialgoodsreceiptitem'),
        ),
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier'),
        ),
    ]
