# Generated by Django 4.2.4 on 2025-08-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0024_remove_rawmaterialgooditem_raw_material_good_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgooditem',
            name='raw_material_goods_receipt_item',
        ),
    ]
