# Generated by Django 4.2.4 on 2025-08-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_remove_assetinventoryrawmaterial_name_and_more'),
        ('crm', '0012_alter_company_name'),
        ('operating', '0025_remove_rawmaterialgooditem_raw_material_goods_receipt_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgood',
            name='asset_inventory_raw_material_good',
        ),
        migrations.RemoveField(
            model_name='rawmaterialgood',
            name='raw_material',
        ),
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='asset_inventory_raw_material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.assetinventoryrawmaterial'),
        ),
        migrations.CreateModel(
            name='RawMaterialGoodReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='crm.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operating.rawmaterialgoodreceipt'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterialgoodreceipt',
            constraint=models.UniqueConstraint(fields=('supplier', 'receipt_number'), name='unique_supplier_receipt_number'),
        ),
    ]
