# Generated by Django 4.2.4 on 2025-08-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_assetinventoryrawmaterial_sku'),
        ('operating', '0026_remove_rawmaterialgood_asset_inventory_raw_material_good_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgooditem',
            name='asset_inventory_raw_material',
        ),
        migrations.AddField(
            model_name='rawmaterialgoodreceipt',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.book'),
        ),
        migrations.AlterField(
            model_name='rawmaterialgooditem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='operating.rawmaterialgoodreceipt'),
        ),
    ]
