# Generated by Django 4.2.4 on 2025-08-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0027_remove_rawmaterialgooditem_asset_inventory_raw_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgooditem',
            name='supplier',
        ),
    ]
