# Generated by Django 4.2.4 on 2025-08-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0028_remove_rawmaterialgooditem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialgooditem',
            name='raw_material_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operating.rawmaterialgood'),
        ),
        migrations.AlterField(
            model_name='rawmaterialgooditem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operating.rawmaterialgoodreceipt'),
        ),
    ]
