# Generated by Django 4.2.4 on 2025-08-16 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0029_rawmaterialgooditem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialgood',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
