# Generated by Django 4.2.4 on 2025-08-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0030_alter_rawmaterialgood_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgoodreceipt',
            name='approved',
        ),
    ]
