# Generated by Django 4.2.4 on 2025-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0031_remove_rawmaterialgoodreceipt_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialgoodreceipt',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialgoodreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
