# Generated by Django 4.2.4 on 2025-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0032_rawmaterialgoodreceipt_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialgooditem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
