# Generated by Django 4.2.4 on 2025-08-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_remove_liabilityaccountspayable_balance'),
        ('operating', '0033_alter_rawmaterialgooditem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialgooditem',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
        migrations.AlterField(
            model_name='rawmaterialgood',
            name='raw_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default='direct'),
        ),
        migrations.AlterField(
            model_name='rawmaterialgood',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('units', 'Unit'), ('mt', 'Meter'), ('kg', 'Kilogram'), ('l', 'Liter'), ('bx', 'Box')], default='units', null=True),
        ),
    ]
