# Generated by Django 4.2.4 on 2025-08-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_remove_liabilityaccountspayable_balance'),
        ('operating', '0034_rawmaterialgooditem_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterialgooditem',
            name='currency',
        ),
        migrations.AddField(
            model_name='rawmaterialgoodreceipt',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.currencycategory'),
        ),
    ]
