# Generated by Django 4.2.25 on 2025-11-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0021_add_web_order_fields'),
        ('operating', '0035_remove_rawmaterialgooditem_currency_and_more'),
    ]

    operations = [
    ]
