# Generated by Django 4.2.25 on 2025-12-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0036_merge_20251115_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ettn',
            field=models.CharField(blank=True, help_text='e-Arşiv Fatura Tanımlama Numarası (ETTN)', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='e-Arşiv Fatura oluşturma tarihi', null=True),
        ),
    ]
