# Generated by Django 5.2.7 on 2025-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0037_order_ettn_order_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('yurtici', 'Yurtiçi Kargo'), ('mng', 'MNG Kargo'), ('aras', 'Aras Kargo'), ('ptt', 'PTT Kargo'), ('ups', 'UPS'), ('other', 'Diğer')], help_text='Kargo şirketi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Müşteri sipariş numarası (DK0000001 formatında)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('in_transit', 'Yolda'), ('out_for_delivery', 'Dağıtımda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi'), ('returned', 'İade Edildi')], default='pending', help_text='Müşteriye gösterilen sipariş durumu', max_length=32),
        ),
    ]
