# Generated by Django 5.2.7 on 2025-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0038_order_carrier_order_order_number_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email address for guest orders', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_first_name',
            field=models.CharField(blank=True, help_text='First name for guest orders', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_last_name',
            field=models.CharField(blank=True, help_text='Last name for guest orders', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone number for guest orders', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_guest_order',
            field=models.BooleanField(default=False, help_text='True if order was placed by guest (non-registered user)'),
        ),
    ]
