# Generated by Django 4.2.25 on 2025-12-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0039_order_guest_email_order_guest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_fabric_used_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kullanılan kumaş miktarı (metre)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Perde boyu (cm)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_mounting_type',
            field=models.CharField(blank=True, choices=[('cornice', 'Korniş'), ('rustic', 'Rustik')], help_text='Montaj tipi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_pleat_density',
            field=models.CharField(blank=True, help_text='Pile yoğunluğu (örn: 1x2, 1x2.5, 1x3)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_pleat_type',
            field=models.CharField(blank=True, choices=[('flat', 'Yatık Pile'), ('kanun', 'Kanun Pile'), ('pipe', 'Boru Pile'), ('water_wave', 'Su Dalgası'), ('american', 'Amerikan Pile'), ('extrafor', 'Ekstrafor')], help_text='Pile tipi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Perde eni (cm)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_wing_type',
            field=models.CharField(blank=True, choices=[('single', 'Tek Kanat'), ('double', 'Çift Kanat')], help_text='Kanat tipi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_custom_curtain',
            field=models.BooleanField(default=False, help_text='Bu bir özel perde siparişi mi?'),
        ),
    ]
