# Generated by Django 4.2.25 on 2026-01-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0050_alter_product_title'),
        ('operating', '0040_add_custom_curtain_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_manufacturing', models.BooleanField(default=False, help_text='If enabled, this product can be manufactured from raw materials.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='marketing.product')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterialsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Amount of raw material used to produce 1 unit of the product', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operating.billofmaterials')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_usages', to='operating.rawmaterialgood')),
            ],
        ),
    ]
