# Generated by Django 5.2.7 on 2026-04-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0041_billofmaterials_billofmaterialsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchase_currency', models.CharField(choices=[('USD', 'USD'), ('TRY', 'TRY'), ('EUR', 'EUR')], default='USD', max_length=4)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost in USD', max_digits=14, null=True)),
                ('cost_try', models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost in TRY', max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='operating.warehouse')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['warehouse', 'sku'], name='operating_w_warehou_ccb25b_idx')],
            },
        ),
    ]
