# Generated by Django 5.2.7 on 2026-04-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_alter_liabilityaccountspayable_supplier'),
        ('operating', '0042_warehouse_created_at_warehouseproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='accounting_book',
            field=models.ForeignKey(blank=True, help_text="Optional: accounting book this warehouse's value is tied to", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='accounting.book'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
