# Generated by Django 5.2.7 on 2026-05-18 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0043_warehouse_accounting_book_warehouse_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.DecimalField(decimal_places=2, help_text='Length of this roll in meters', max_digits=10)),
                ('lot_number', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.ImageField(blank=True, help_text='The captured label image (kept for audit)', null=True, upload_to='roll_scans/%Y/%m/')),
                ('ocr_raw', models.TextField(blank=True, help_text='Raw OCR text — useful for debugging misreads', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='operating.warehouseproduct')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_rolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['product', '-scanned_at'], name='operating_w_product_7a35a1_idx')],
            },
        ),
    ]
