# Generated by Django 5.2.7 on 2026-05-19 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0044_warehouseproductroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock in'), ('out', 'Stock out'), ('adjustment', 'Adjustment')], db_index=True, max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, help_text='Free-form reference, e.g. order number, document id', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='warehouseproductroll',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproductroll',
            name='meters_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length still on the roll (drops as stock-outs happen)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproductroll',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('partial', 'Partially used'), ('consumed', 'Fully consumed')], db_index=True, default='in_stock', max_length=16),
        ),
        migrations.AlterField(
            model_name='warehouseproductroll',
            name='meters',
            field=models.DecimalField(decimal_places=2, help_text='Initial length of this roll in meters', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='warehouseproductroll',
            index=models.Index(fields=['barcode'], name='operating_w_barcode_39d55b_idx'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='operating.warehouseproduct'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='roll',
            field=models.ForeignKey(blank=True, help_text='The specific roll affected, when applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='operating.warehouseproductroll'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-created_at'], name='operating_s_product_16cc36_idx'),
        ),
    ]
