# Generated by Django 5.2.7 on 2026-05-25 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0007_alter_carimovement_movement_type'),
        ('operating', '0045_stockmovement_warehouseproductroll_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cari',
            field=models.ForeignKey(blank=True, help_text='Linked current account (auto-resolved from contact/company)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='current_account.cariaccount'),
        ),
    ]
