# Generated by Django 5.2.7 on 2026-05-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0046_order_cari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('packaging', 'Packaging'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', help_text='Müşteriye gösterilen sipariş durumu', max_length=32),
        ),
    ]
