# Generated by Django 5.2.7 on 2026-05-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0047_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packed_assignment', to='operating.orderitem')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packed_order_items', to='operating.pack')),
            ],
            options={
                'ordering': ['pack__pack_number', 'id'],
            },
        ),
    ]
