# Generated by Django 5.2.7 on 2026-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0048_packedorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_consumed_at',
            field=models.DateTimeField(blank=True, help_text="When catalog stock was deducted for this order's items.", null=True),
        ),
    ]
