# Generated by Django 4.2.25 on 2026-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0049_order_stock_consumed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notify_customer',
            field=models.BooleanField(default=False, help_text='Send transactional emails to the customer for this order.'),
        ),
    ]
