# Generated by Django 4.2.25 on 2026-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0050_order_notify_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
