# Generated by Django 5.2.7 on 2026-06-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0073_unique_variant_sku'),
        ('operating', '0051_pack_code_pack_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='catalog_variant',
            field=models.ForeignKey(blank=True, help_text='Hidden marketing ProductVariant auto-created from roll scans.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_products', to='marketing.productvariant'),
        ),
    ]
