# Generated by Django 5.2.7 on 2026-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0052_warehouseproduct_catalog_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='print_header',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
