# Generated by Django 5.2.7 on 2026-07-01 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0053_order_print_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRollReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.DecimalField(decimal_places=2, help_text='Metres reserved (cut) from this roll for the order.', max_digits=10)),
                ('consumed', models.BooleanField(db_index=True, default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_reservations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_reservations', to='operating.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='The order line this roll helps fulfil (best-effort).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_reservations', to='operating.orderitem')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='operating.warehouseproductroll')),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='operating.warehouseproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'consumed'], name='operating_o_order_i_3ecd8f_idx'), models.Index(fields=['warehouse_product', 'consumed'], name='operating_o_warehou_9fea4f_idx'), models.Index(fields=['roll', 'consumed'], name='operating_o_roll_id_9a1d3d_idx')],
            },
        ),
    ]
