# Generated by Django 5.2.7 on 2026-07-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0073_unique_variant_sku'),
        ('operating', '0053_order_print_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('web', 'Web'), ('retail', 'Perakende')], db_index=True, default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_order_items', to='operating.warehouseproduct'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketing.product'),
        ),
        migrations.CreateModel(
            name='RetailScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_scans', to='operating.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_scans', to='operating.orderitem')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_scans', to='operating.warehouseproductroll')),
                ('warehouse_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_scans', to='operating.warehouseproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
