# Generated by Django 5.2.7 on 2026-07-06 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0054_orderrollreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Order created'), ('status', 'Status changed'), ('item_added', 'Item added'), ('item_removed', 'Item removed'), ('item_updated', 'Item updated'), ('field', 'Field updated')], db_index=True, max_length=16)),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('item_label', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='operating.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='operating_o_order_i_f477e9_idx')],
            },
        ),
    ]
