# Generated by Django 5.2.7 on 2026-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0055_orderchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_retail_order',
            field=models.BooleanField(default=False, help_text='True if order was created via the Perakende (retail/walk-in) toggle on the create-order form'),
        ),
    ]
