# Generated by Django 5.2.7 on 2026-07-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0056_order_is_retail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrollreservation',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_reservations', to='operating.pack'),
        ),
    ]
