# Generated by Django 5.2.7 on 2026-07-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_account', '0009_alter_invoice_series'),
        ('operating', '0057_orderrollreservation_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductroll',
            name='purchase_invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_rolls', to='current_account.invoiceitem'),
        ),
    ]
