# Generated by Django 5.2.7 on 2026-07-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0058_warehouseproductroll_purchase_invoice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
