# Generated by Django 5.2.7 on 2026-07-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0059_order_original_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='operating.pack'),
        ),
    ]
