# Generated by Django 5.2.7 on 2026-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0060_orderitem_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='combined_sources',
            field=models.ManyToManyField(blank=True, help_text='Member warehouses this combined (ortak) warehouse merges', related_name='combined_views', to='operating.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('combined', 'Ortak (birleşik)')], db_index=True, default='normal', max_length=12),
        ),
    ]
