# Generated by Django 4.2.25 on 2026-07-31 12:55

from django.db import migrations, models


def backfill_order_date(apps, schema_editor):
    """Set order_date = created_at.date() for existing orders."""
    Order = apps.get_model('operating', 'Order')
    for o in Order.objects.filter(order_date__isnull=True).only('id', 'created_at'):
        if o.created_at:
            Order.objects.filter(pk=o.pk).update(order_date=o.created_at.date())


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0061_warehouse_combined_sources_warehouse_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_order_date, reverse_code=migrations.RunPython.noop),
    ]
