# Generated by Django 4.2.25 on 2026-08-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0062_add_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductroll',
            name='is_second',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
