# Generated by Django 4.2.25 on 2026-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0063_add_roll_is_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='cost_try',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost in TRY', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost in USD', max_digits=14, null=True),
        ),
    ]
