# Generated by Django 4.2.25 on 2026-08-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0066_backfill_warehouseproduct_cost_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='outsourced_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Depo dışından temin edilecek miktar — faturaya ve cariye dahildir.', max_digits=10, null=True),
        ),
    ]
