# Generated by Django 4.2.25 on 2026-08-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Re-point Order.cari and WarehouseProductRoll.purchase_invoice_item at
    the accounting app — state only.

    Postgres carries foreign key constraints across a table rename
    automatically, so the constraints already reference the renamed tables and
    no DDL is required. Running the AlterField against the database would drop
    and recreate both constraints, taking an ACCESS EXCLUSIVE lock on
    operating_order for no benefit.
    """


    dependencies = [
        ('accounting', '0066_cariaccount_carimovement_invoice_payment_invoiceitem_and_more'),
        ('operating', '0067_orderitem_outsourced_quantity'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='cari',
                    field=models.ForeignKey(blank=True, help_text='Linked current account (auto-resolved from contact/company)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounting.cariaccount'),
                ),
                migrations.AlterField(
                    model_name='warehouseproductroll',
                    name='purchase_invoice_item',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_rolls', to='accounting.invoiceitem'),
                ),
            ],
            database_operations=[],
        ),
    ]
