# Generated by Django 4.2.25 on 2026-08-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0070_stockmovement_order_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billed_line_quantities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billed_quantities_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='The reservation this deduction realised, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='operating.orderrollreservation'),
        ),
    ]
