# Generated by Django 4.2.25 on 2026-09-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0073_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductroll',
            name='image_url',
            field=models.URLField(blank=True, help_text='CDN URL of the captured label image (kept for audit)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproductroll',
            name='source_image',
            field=models.ImageField(blank=True, help_text='The captured label image, stored locally (legacy)', null=True, upload_to='roll_scans/%Y/%m/'),
        ),
    ]
