# Generated by Django 4.2.25 on 2026-09-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0074_warehouseproductroll_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='warehouseproductroll',
            name='operating_w_barcode_39d55b_idx',
        ),
        migrations.AlterField(
            model_name='warehouseproductroll',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
