# Generated by Django 4.2.25 on 2026-09-06 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Adopt the purchasing models from the procurement app.

    Same shape as marketing/0080: the CreateModel operations are STATE ONLY,
    telling Django these five models (plus the two auto-created m2m tables)
    belong to `operating` now, while the database side only renames the
    physical tables.

    These tables are empty today, so nothing rides on the rename — but it is
    done properly rather than by dropping and recreating, so the migration
    behaves the same way on a database where purchasing has been used.

    No index renames are needed: the models declare no Meta indexes, and the
    two m2m unique constraints are found by introspecting columns rather than
    by name.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0019_company_created_by_contact_created_by'),
        ('marketing', '0082_drop_superseded_mail_indexes'),
        ('operating', '0075_remove_warehouseproductroll_operating_w_barcode_39d55b_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PurchaseOrder',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order_date', models.DateField(auto_now_add=True)),
                        ('expected_delivery_date', models.DateField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('confirmed', 'Confirmed by Supplier'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                        ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('currency', models.CharField(default='USD', max_length=10)),
                        ('shipping_address', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='PurchaseRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('department', models.CharField(blank=True, max_length=100)),
                        ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                        ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                        ('requested_date', models.DateField(auto_now_add=True)),
                        ('needed_by', models.DateField(blank=True, null=True)),
                        ('reason', models.TextField(blank=True, help_text='Justification for the request')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('approved_at', models.DateTimeField(blank=True, null=True)),
                        ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL)),
                        ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='RequestForQuotation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('deadline', models.DateField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Suppliers'), ('closed', 'Closed')], default='draft', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('requests', models.ManyToManyField(blank=True, related_name='rfqs', to='operating.purchaserequest')),
                        ('suppliers', models.ManyToManyField(related_name='rfqs', to='crm.supplier')),
                    ],
                ),
                migrations.CreateModel(
                    name='PurchaseRequestItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('description', models.CharField(blank=True, help_text='Description if item not in system', max_length=255)),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('unit', models.CharField(default='unit', max_length=20)),
                        ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                        ('product', models.ForeignKey(blank=True, help_text='Select if buying a finished product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.product')),
                        ('raw_material', models.ForeignKey(blank=True, help_text='Select if buying raw material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operating.rawmaterialgood')),
                        ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operating.purchaserequest')),
                    ],
                ),
                migrations.CreateModel(
                    name='PurchaseOrderItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('item_description', models.CharField(max_length=255)),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                        ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operating.purchaseorder')),
                        ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='operating.purchaserequestitem')),
                    ],
                ),
                migrations.AddField(
                    model_name='purchaseorder',
                    name='rfq',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='operating.requestforquotation'),
                ),
                migrations.AddField(
                    model_name='purchaseorder',
                    name='supplier',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='crm.supplier'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "procurement_purchaseorder" RENAME TO "operating_purchaseorder";',
                        'ALTER TABLE "procurement_purchaseorderitem" RENAME TO "operating_purchaseorderitem";',
                        'ALTER TABLE "procurement_purchaserequest" RENAME TO "operating_purchaserequest";',
                        'ALTER TABLE "procurement_purchaserequestitem" RENAME TO "operating_purchaserequestitem";',
                        'ALTER TABLE "procurement_requestforquotation" RENAME TO "operating_requestforquotation";',
                        'ALTER TABLE "procurement_requestforquotation_requests" RENAME TO "operating_requestforquotation_requests";',
                        'ALTER TABLE "procurement_requestforquotation_suppliers" RENAME TO "operating_requestforquotation_suppliers";',
                    ],
                    reverse_sql=[
                        'ALTER TABLE "operating_purchaseorder" RENAME TO "procurement_purchaseorder";',
                        'ALTER TABLE "operating_purchaseorderitem" RENAME TO "procurement_purchaseorderitem";',
                        'ALTER TABLE "operating_purchaserequest" RENAME TO "procurement_purchaserequest";',
                        'ALTER TABLE "operating_purchaserequestitem" RENAME TO "procurement_purchaserequestitem";',
                        'ALTER TABLE "operating_requestforquotation" RENAME TO "procurement_requestforquotation";',
                        'ALTER TABLE "operating_requestforquotation_requests" RENAME TO "procurement_requestforquotation_requests";',
                        'ALTER TABLE "operating_requestforquotation_suppliers" RENAME TO "procurement_requestforquotation_suppliers";',
                    ],
                ),
            ],
        ),
    ]
