# Generated by Django 4.2.25 on 2026-09-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0077_move_purchasing_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductroll',
            name='unit_cost_base',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Unit cost when received, in the owning book's base currency", max_digits=14, null=True),
        ),
    ]
