# Generated by Django 4.2.25 on 2026-09-07 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0097_retail_auto_collection_desc_in_english'),
        ('operating', '0080_rename_roll_to_stock_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderstockreservation',
            name='operating_o_roll_id_9a1d3d_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstockreservation',
            new_name='operating_o_order_i_65b4aa_idx',
            old_name='operating_o_order_i_3ecd8f_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstockreservation',
            new_name='operating_o_warehou_847695_idx',
            old_name='operating_o_warehou_9fea4f_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouseproductitem',
            new_name='operating_w_product_79e99c_idx',
            old_name='operating_w_product_7a35a1_idx',
        ),
        migrations.AlterField(
            model_name='orderstockreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderstockreservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='operating.order'),
        ),
        migrations.AlterField(
            model_name='orderstockreservation',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='The order line this roll helps fulfil (best-effort).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='operating.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderstockreservation',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='operating.pack'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_item',
            field=models.ForeignKey(blank=True, help_text='The specific stock item affected, when applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='operating.warehouseproductitem'),
        ),
        migrations.AlterField(
            model_name='warehouseproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='operating.warehouseproduct'),
        ),
        migrations.AlterField(
            model_name='warehouseproductitem',
            name='purchase_invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stock_items', to='accounting.invoiceitem'),
        ),
        migrations.AlterField(
            model_name='warehouseproductitem',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_stock_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderstockreservation',
            index=models.Index(fields=['stock_item', 'consumed'], name='operating_o_stock_i_b781ec_idx'),
        ),
    ]
