# Generated by Django 4.2.25 on 2026-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0083_quantity_not_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='split_group',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
