# Generated by Django 4.2.25 on 2026-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0084_order_split_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='ORD', max_length=10)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('next_seq', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Order number sequence',
                'verbose_name_plural': 'Order number sequence',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Customer-facing order reference, e.g. ORD-2026-000001', max_length=20, null=True, unique=True),
        ),
    ]
