# Generated by Django 4.2.25 on 2026-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0086_warehouseproduct_pack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='unit',
            field=models.CharField(choices=[('mt', 'Metre'), ('adet', 'Piece'), ('paket', 'Pack'), ('kg', 'Kilogram')], default='mt', help_text='What this product is counted in', max_length=8),
        ),
    ]
