# Generated by Django 4.2.25 on 2026-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0089_english_unit_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='outsourced_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Quantity sourced from outside the warehouse — included in the invoice and the current account.', max_digits=10, null=True),
        ),
    ]
