# Generated by Django 4.2.25 on 2026-09-12 18:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0090_outsourced_quantity_help_in_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='cost_try',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost in TRY', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost in USD', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='warehouseproductitem',
            name='unit_cost_base',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Unit cost when received, in the owning book's base currency", max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='warehouseproduct',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0), ('purchase_price__isnull', True), _connector='OR'), name='operating_warehouseproduct_purchase_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='warehouseproduct',
            constraint=models.CheckConstraint(check=models.Q(('cost_usd__gte', 0), ('cost_usd__isnull', True), _connector='OR'), name='operating_warehouseproduct_cost_usd_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='warehouseproduct',
            constraint=models.CheckConstraint(check=models.Q(('cost_try__gte', 0), ('cost_try__isnull', True), _connector='OR'), name='operating_warehouseproduct_cost_try_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='warehouseproductitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost_base__gte', 0), ('unit_cost_base__isnull', True), _connector='OR'), name='operating_warehouseproductitem_unit_cost_base_not_negative'),
        ),
    ]
