# Generated by Django 4.2.25 on 2026-09-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0092_unit_and_pack_read_from_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='print_header',
        ),
    ]
