# Generated by Django 4.2.25 on 2026-09-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0108_drop_invoice_language'),
        ('operating', '0094_combined_warehouse_has_no_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(blank=True, help_text="The currency this order's prices are in (the customer's own).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounting.currencycategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Rate from this order's currency to base, as at the order date.", max_digits=16, null=True),
        ),
    ]
