# Generated by Django 4.2.25 on 2026-09-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0095_order_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What it is called on the invoice, e.g. “Delivery” or “Partnership discount”.', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text="In the order's currency. Positive adds to the total, negative takes off.", max_digits=12)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='operating.order')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
