# Generated by Django 4.2.25 on 2026-09-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0095_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductitem',
            name='supplier_barcode',
            field=models.CharField(blank=True, db_index=True, help_text="The supplier's own code for this roll, as printed", max_length=64, null=True),
        ),
    ]
