# Generated by Django 4.2.25 on 2026-09-20 23:48
#
# Two 0096s were written the same day on two machines, both on top of
# 0095_order_currency: OrderAdjustment and WarehouseProductItem
# .supplier_barcode. They touch different tables and neither needs the
# other, so the graph just needs one leaf again -- nothing to do.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0096_order_adjustment'),
        ('operating', '0096_warehouseproductitem_supplier_barcode'),
    ]

    operations = [
    ]
