# Generated by Django 4.2.25 on 2026-09-26 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

# Written out, not imported from operating.models: a migration must seed
# what the list was on the day, whatever the module says later.
SEED = [
    ("yurtici", "Yurtiçi Kargo", True),
    ("mng", "MNG Kargo", True),
    ("aras", "Aras Kargo", True),
    ("ptt", "PTT Kargo", True),
    ("ups", "UPS", True),
    # Kept for the orders already saved as "other"; not offered any more —
    # a carrier missing from the list is typed in by name instead.
    ("other", "Diğer", False),
]


def seed(apps, schema_editor):
    Carrier = apps.get_model("operating", "Carrier")
    for code, name, active in SEED:
        Carrier.objects.get_or_create(code=code, defaults={"name": name, "is_active": active})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operating', '0098_order_cargo_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Kargo şirketi', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
