# Generated by Django 4.2.25 on 2026-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0101_order_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Carrier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ettn',
            field=models.CharField(blank=True, help_text='e-Archive invoice identification number (ETTN)', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date the e-Archive invoice was created', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_retail_order',
            field=models.BooleanField(default=False, help_text='True if order was created via the retail (walk-in) toggle on the create-order form'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('packaging', 'Packaging'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', help_text='The order status shown to the customer', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_fabric_used_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fabric used (metres)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Curtain height (cm)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_mounting_type',
            field=models.CharField(blank=True, choices=[('cornice', 'Cornice'), ('rustic', 'Rustic')], help_text='Mounting type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_pleat_density',
            field=models.CharField(blank=True, help_text='Pleat density (e.g. 1x2, 1x2.5, 1x3)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_pleat_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat pleat'), ('kanun', 'Kanun pleat'), ('pipe', 'Pipe pleat'), ('water_wave', 'Water wave'), ('american', 'American pleat'), ('extrafor', 'Extrafor')], help_text='Pleat type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Curtain width (cm)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_wing_type',
            field=models.CharField(blank=True, choices=[('single', 'Single panel'), ('double', 'Double panel')], help_text='Panel type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_custom_curtain',
            field=models.BooleanField(default=False, help_text='Is this a custom curtain order?'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='combined_sources',
            field=models.ManyToManyField(blank=True, help_text='Member warehouses this combined warehouse merges', related_name='combined_views', to='operating.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('combined', 'Combined')], db_index=True, default='normal', max_length=12),
        ),
    ]
