# Generated by Django 4.2.4 on 2025-03-07 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('guest', 'Guest')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, choices=[('admin', 'Has full access to all resources and settings.'), ('manager', 'Can manage teams and projects, but has limited access to settings.'), ('employee', 'Can access and manage their own tasks and projects.'), ('guest', 'Has limited access to view certain resources.')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.ManyToManyField(blank=True, related_name='members', to='authentication.permission')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
