# Generated by Django 5.2.7 on 2025-11-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_webclient_address_webclient_birthdate_webclient_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webclient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='webclient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='webclient',
            name='country',
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='authentication.webclient')),
            ],
            options={
                'verbose_name': 'Client Address',
                'verbose_name_plural': 'Client Addresses',
                'db_table': 'client_address',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
