# Generated by Django 5.2.7 on 2025-11-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_webclient_address_remove_webclient_city_and_more'),
    ]

    operations = [
    ]
