# Generated by Django 5.2.7 on 2025-11-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20251112_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='authentication.webclient')),
            ],
            options={
                'verbose_name': 'Client Favorite',
                'verbose_name_plural': 'Client Favorites',
                'db_table': 'client_favorite',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'product_sku')},
            },
        ),
    ]
