# Generated by Django 4.2.4 on 2025-02-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_accesslevel_member_access_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='description',
            field=models.TextField(blank=True, choices=[('admin', 'Has full access to all resources and settings.'), ('manager', 'Can manage teams and projects, but has limited access to settings.'), ('employee', 'Can access and manage their own tasks and projects.'), ('guest', 'Has limited access to view certain resources.')], null=True),
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('guest', 'Guest')], max_length=100, unique=True),
        ),
    ]
