# Generated by Django 4.2.4 on 2025-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_accesslevel_description_alter_accesslevel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_levels',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='authentication.accesslevel'),
        ),
    ]
