# Generated by Django 4.2.4 on 2025-02-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_member_access_levels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessLevel',
            new_name='Permission',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='access_levels',
            new_name='permissions',
        ),
    ]
