# Generated by Django 4.2.25 on 2025-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webclient',
            name='web_client_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
