# Generated by Django 4.2.4 on 2025-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_accesslevel_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='members', to='authentication.permission'),
        ),
    ]
