# Generated by Django 5.2.7 on 2026-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_googlechatcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlechatcredentials',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlechatcredentials',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
