# Generated by Django 5.2.7 on 2026-02-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_googlechatcredentials_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlechatcredentials',
            name='client_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlechatcredentials',
            name='client_secret',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlechatcredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlechatcredentials',
            name='token_uri',
            field=models.TextField(),
        ),
    ]
