# Generated by Django 5.2.7 on 2026-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_googlechatcredentials_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlechatcredentials',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
