# Generated by Django 4.2.25 on 2026-08-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0075_rename_cari_ledger_to_default_cari_target'),
        ('authentication', '0014_alter_googlechatcredentials_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_book',
            field=models.ForeignKey(blank=True, help_text='Orders this member creates are booked here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounting.book', verbose_name='Working book'),
        ),
    ]
