# Generated by Django 4.2.25 on 2026-08-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0093_alter_invoiceitem_unit_price'),
        ('authentication', '0017_seed_purchase_confirm_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='books',
            field=models.ManyToManyField(blank=True, help_text='Books this member may work in.', related_name='assigned_members', to='accounting.book', verbose_name='Assigned books'),
        ),
    ]
