# Generated by Django 4.2.25 on 2026-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_permission_description_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, choices=[('admin', 'Has full access to all resources and settings.'), ('manager', 'Can manage teams and projects, but has limited access to settings.'), ('employee', 'Can access and manage their own tasks and projects.'), ('guest', 'Has limited access to view certain resources.'), ('purchase_confirm', 'Can confirm a purchase order into warehouse stock (goods receipt).'), ('sales_rep', 'Can view stock quantities, prices and sales. Cannot change anything.'), ('view_profit', 'Can see cost of goods, gross profit and margin on orders and analytics.')], null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('guest', 'Guest'), ('purchase_confirm', 'Confirm purchases'), ('sales_rep', 'Sales rep (read-only)'), ('view_profit', 'See cost and profit')], max_length=100, unique=True),
        ),
    ]
