# Generated by Django 4.2.25 on 2026-02-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_comment', 'Task Comment'), ('team_invitation', 'Team Invitation')], max_length=30),
        ),
    ]
