"""Cari account service helpers — keep view code thin and signals clean.

The big picture:
- Every Order placed manually (B2B contact/company) should land on the
  customer's cari. If the contact belongs to a company we always book
  the order against the COMPANY so the company sees one consolidated
  cari (the user explicitly asked for this).
- Web orders skip this entirely (they go through create_web_order
  which is not wired to call into here).
- Each call site is responsible for invoking ensure_cari_for_order +
  post_order_movement once on creation; subsequent edits update or
  re-create the movement.
"""
from __future__ import annotations

from datetime import date
from decimal import Decimal

from django.contrib.contenttypes.models import ContentType
from django.db import transaction

from accounting.models import Book, CurrencyCategory

from .models import CariAccount, CariMovement, CariSettings


# ---------------------------------------------------------------------------
# Book — the user wants a single shared book; no UI for selecting one.
# ---------------------------------------------------------------------------
def get_default_book() -> Book:
    """Return the singleton default Book, creating one if none exists.

    User constraint: the project has *one* book company-wide. We don't
    expose Book selection in cari/order UI any more. Picking the
    lowest-id row gives us deterministic behaviour even if multiple
    rows happen to exist in legacy data.
    """
    book = Book.objects.order_by("id").first()
    if book:
        return book
    return Book.objects.create(name="Main Book")


def _resolve_currency(order=None) -> CurrencyCategory:
    """Pick a CurrencyCategory for new movements/cari accounts.

    Order doesn't have a currency field — orders are stored in USD by
    convention (per the rest of the codebase). Fall back to whichever
    currency is marked "USD"/base, or the first row.
    """
    base_code = "USD"
    cur = CurrencyCategory.objects.filter(code=base_code).first()
    if cur:
        return cur
    cur = CurrencyCategory.objects.filter(is_base_currency=True).first() \
        if hasattr(CurrencyCategory, "is_base_currency") else None
    return cur or CurrencyCategory.objects.first()


# ---------------------------------------------------------------------------
# Cari resolution
# ---------------------------------------------------------------------------
def get_or_create_cari_for_order(order, *, member=None) -> CariAccount | None:
    """Find (or create) the cari for an order's customer.

    Resolution priority (per user spec):
      1. If the order's contact is tied to a company → use COMPANY's cari.
      2. Else if order.company → use that.
      3. Else if order.contact → use contact's cari.
      4. Else → return None (web_client / no customer = skip).

    The CariAccount unique-constraints (one cari per book+entity)
    guarantee idempotency: calling this multiple times for the same
    customer reuses the existing row.
    """
    contact = getattr(order, "contact", None)
    company = getattr(order, "company", None) or (
        getattr(contact, "company", None) if contact else None
    )

    book = get_default_book()
    currency = _resolve_currency(order)

    if company:
        cari = CariAccount.objects.filter(book=book, company=company).first()
        if cari:
            return cari
        # code is auto-generated by the pre_save signal via CariSettings.
        return CariAccount.objects.create(
            book=book, company=company,
            name=getattr(company, "name", "") or f"Company #{company.pk}",
            type="customer",
            default_currency=currency,
            created_by=member,
        )

    if contact:
        cari = CariAccount.objects.filter(book=book, contact=contact).first()
        if cari:
            return cari
        return CariAccount.objects.create(
            book=book, contact=contact,
            name=getattr(contact, "name", "") or f"Contact #{contact.pk}",
            type="customer",
            default_currency=currency,
            created_by=member,
        )

    return None


# ---------------------------------------------------------------------------
# Movements — keep the order ↔ movement mapping atomic + idempotent.
# ---------------------------------------------------------------------------
def _order_movement(order):
    """Return the existing 'order_sale' movement for this order, if any.

    Uses CariMovement's generic source FK so we can look the row up
    without storing a pointer on Order itself.
    """
    if not order or not order.pk:
        return None
    ct = ContentType.objects.get_for_model(order.__class__)
    return CariMovement.objects.filter(
        source_type=ct, source_id=order.pk, movement_type="order_sale",
    ).first()


@transaction.atomic
def post_order_movement(order, *, member=None):
    """Create (or update) the cari movement that represents this order.

    Sign convention: order_sale is a debit on the customer (+ amount —
    the customer owes us more once the order goes out). This mirrors
    invoice_sale; the customer's cari balance reflects pending orders
    even before a formal invoice is issued.

    Idempotent: re-running after an edit updates the amount in place
    instead of creating a duplicate movement.
    """
    if not order or not order.pk:
        return None

    cari = order.cari
    if not cari:
        return None

    # Compute total from the order. Use the model's total_value() so
    # we stay consistent with what the UI displays.
    try:
        total = Decimal(str(order.total_value() or 0))
    except Exception:
        total = Decimal("0")

    existing = _order_movement(order)

    if total <= 0:
        # An empty order shouldn't sit on the ledger — clean it up.
        if existing:
            existing.delete()
            cari.recompute_balance(save=True)
        return None

    book = get_default_book()
    currency = _resolve_currency(order)
    ref = order.order_number or f"ORD-{order.pk}"
    desc = f"Order #{order.pk}"

    if existing:
        # Update in place — keeps the movement's id stable and avoids
        # phantom rows in the ledger UI.
        existing.amount = total
        existing.currency = currency
        existing.book = book
        existing.date = order.created_at.date() if order.created_at else date.today()
        existing.description = desc
        existing.reference = ref
        # Force amount_base recompute on save.
        existing.amount_base = Decimal("0")
        existing.save()
        return existing

    return CariMovement.objects.create(
        cari=cari,
        book=book,
        date=order.created_at.date() if order.created_at else date.today(),
        amount=total,
        currency=currency,
        movement_type="order_sale",
        source_type=ContentType.objects.get_for_model(order.__class__),
        source_id=order.pk,
        description=desc,
        reference=ref,
        created_by=member,
    )


def reverse_order_movement(order):
    """Delete the cari movement tied to this order (e.g. on order
    deletion or cancellation). Cari balance is recomputed inside
    CariMovement.delete via the standard model flow."""
    mv = _order_movement(order)
    if not mv:
        return
    cari = mv.cari
    mv.delete()
    if cari:
        cari.recompute_balance(save=True)
